/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Solifyn.Client;
using Solifyn.Model;

namespace Solifyn.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDiscordIntegrationApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Discord Bot Installation URL
        /// </summary>
        /// <remarks>
        /// Generates the URL to invite the system-wide Discord Bot onto the merchant&#39;s Discord server.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId">Optional Product ID to redirect back to after installation (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void DiscordGetInstallUrl(string productId = default(string), int operationIndex = 0);

        /// <summary>
        /// Get Discord Bot Installation URL
        /// </summary>
        /// <remarks>
        /// Generates the URL to invite the system-wide Discord Bot onto the merchant&#39;s Discord server.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId">Optional Product ID to redirect back to after installation (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DiscordGetInstallUrlWithHttpInfo(string productId = default(string), int operationIndex = 0);
        /// <summary>
        /// List Guild Discord Roles
        /// </summary>
        /// <remarks>
        /// Retrieves all roles available in the connected merchant&#39;s Discord server/guild.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;DiscordRolesResponseDto&gt;</returns>
        List<DiscordRolesResponseDto> DiscordListRoles(int operationIndex = 0);

        /// <summary>
        /// List Guild Discord Roles
        /// </summary>
        /// <remarks>
        /// Retrieves all roles available in the connected merchant&#39;s Discord server/guild.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;DiscordRolesResponseDto&gt;</returns>
        ApiResponse<List<DiscordRolesResponseDto>> DiscordListRolesWithHttpInfo(int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDiscordIntegrationApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Discord Bot Installation URL
        /// </summary>
        /// <remarks>
        /// Generates the URL to invite the system-wide Discord Bot onto the merchant&#39;s Discord server.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId">Optional Product ID to redirect back to after installation (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DiscordGetInstallUrlAsync(string productId = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Discord Bot Installation URL
        /// </summary>
        /// <remarks>
        /// Generates the URL to invite the system-wide Discord Bot onto the merchant&#39;s Discord server.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId">Optional Product ID to redirect back to after installation (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DiscordGetInstallUrlWithHttpInfoAsync(string productId = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// List Guild Discord Roles
        /// </summary>
        /// <remarks>
        /// Retrieves all roles available in the connected merchant&#39;s Discord server/guild.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;DiscordRolesResponseDto&gt;</returns>
        System.Threading.Tasks.Task<List<DiscordRolesResponseDto>> DiscordListRolesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// List Guild Discord Roles
        /// </summary>
        /// <remarks>
        /// Retrieves all roles available in the connected merchant&#39;s Discord server/guild.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;DiscordRolesResponseDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<DiscordRolesResponseDto>>> DiscordListRolesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDiscordIntegrationApi : IDiscordIntegrationApiSync, IDiscordIntegrationApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DiscordIntegrationApi : IDiscordIntegrationApi
    {
        private Solifyn.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DiscordIntegrationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DiscordIntegrationApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DiscordIntegrationApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DiscordIntegrationApi(string basePath)
        {
            this.Configuration = Solifyn.Client.Configuration.MergeConfigurations(
                Solifyn.Client.GlobalConfiguration.Instance,
                new Solifyn.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Solifyn.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Solifyn.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Solifyn.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DiscordIntegrationApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DiscordIntegrationApi(Solifyn.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Solifyn.Client.Configuration.MergeConfigurations(
                Solifyn.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Solifyn.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Solifyn.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Solifyn.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DiscordIntegrationApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DiscordIntegrationApi(Solifyn.Client.ISynchronousClient client, Solifyn.Client.IAsynchronousClient asyncClient, Solifyn.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Solifyn.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Solifyn.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Solifyn.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Solifyn.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Solifyn.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Discord Bot Installation URL Generates the URL to invite the system-wide Discord Bot onto the merchant&#39;s Discord server.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId">Optional Product ID to redirect back to after installation (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void DiscordGetInstallUrl(string productId = default(string), int operationIndex = 0)
        {
            DiscordGetInstallUrlWithHttpInfo(productId);
        }

        /// <summary>
        /// Get Discord Bot Installation URL Generates the URL to invite the system-wide Discord Bot onto the merchant&#39;s Discord server.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId">Optional Product ID to redirect back to after installation (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Solifyn.Client.ApiResponse<Object> DiscordGetInstallUrlWithHttpInfo(string productId = default(string), int operationIndex = 0)
        {
            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (productId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Solifyn.Client.ClientUtils.ParameterToMultiMap("", "productId", productId));
            }

            localVarRequestOptions.Operation = "DiscordIntegrationApi.DiscordGetInstallUrl";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Object>("/v1/discord/install", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DiscordGetInstallUrl", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Discord Bot Installation URL Generates the URL to invite the system-wide Discord Bot onto the merchant&#39;s Discord server.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId">Optional Product ID to redirect back to after installation (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DiscordGetInstallUrlAsync(string productId = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            await DiscordGetInstallUrlWithHttpInfoAsync(productId, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Get Discord Bot Installation URL Generates the URL to invite the system-wide Discord Bot onto the merchant&#39;s Discord server.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="productId">Optional Product ID to redirect back to after installation (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Solifyn.Client.ApiResponse<Object>> DiscordGetInstallUrlWithHttpInfoAsync(string productId = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (productId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Solifyn.Client.ClientUtils.ParameterToMultiMap("", "productId", productId));
            }

            localVarRequestOptions.Operation = "DiscordIntegrationApi.DiscordGetInstallUrl";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Object>("/v1/discord/install", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DiscordGetInstallUrl", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Guild Discord Roles Retrieves all roles available in the connected merchant&#39;s Discord server/guild.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;DiscordRolesResponseDto&gt;</returns>
        public List<DiscordRolesResponseDto> DiscordListRoles(int operationIndex = 0)
        {
            Solifyn.Client.ApiResponse<List<DiscordRolesResponseDto>> localVarResponse = DiscordListRolesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Guild Discord Roles Retrieves all roles available in the connected merchant&#39;s Discord server/guild.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;DiscordRolesResponseDto&gt;</returns>
        public Solifyn.Client.ApiResponse<List<DiscordRolesResponseDto>> DiscordListRolesWithHttpInfo(int operationIndex = 0)
        {
            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "DiscordIntegrationApi.DiscordListRoles";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<DiscordRolesResponseDto>>("/v1/discord/roles", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DiscordListRoles", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Guild Discord Roles Retrieves all roles available in the connected merchant&#39;s Discord server/guild.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;DiscordRolesResponseDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<DiscordRolesResponseDto>> DiscordListRolesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Solifyn.Client.ApiResponse<List<DiscordRolesResponseDto>> localVarResponse = await DiscordListRolesWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Guild Discord Roles Retrieves all roles available in the connected merchant&#39;s Discord server/guild.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;DiscordRolesResponseDto&gt;)</returns>
        public async System.Threading.Tasks.Task<Solifyn.Client.ApiResponse<List<DiscordRolesResponseDto>>> DiscordListRolesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "DiscordIntegrationApi.DiscordListRoles";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<DiscordRolesResponseDto>>("/v1/discord/roles", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DiscordListRoles", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
