/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Solifyn.Client;
using Solifyn.Model;

namespace Solifyn.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEntitlementsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Entitlement
        /// </summary>
        /// <remarks>
        /// Create a new independent access entitlement.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EntitlementDetailResponseDto</returns>
        EntitlementDetailResponseDto EntitlementsCreate(CreateEntitlementDto createEntitlementDto, int operationIndex = 0);

        /// <summary>
        /// Create Entitlement
        /// </summary>
        /// <remarks>
        /// Create a new independent access entitlement.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EntitlementDetailResponseDto</returns>
        ApiResponse<EntitlementDetailResponseDto> EntitlementsCreateWithHttpInfo(CreateEntitlementDto createEntitlementDto, int operationIndex = 0);
        /// <summary>
        /// Delete Entitlement
        /// </summary>
        /// <remarks>
        /// Delete an independent entitlement and unlink all mapped products.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EntitlementDetailResponseDto</returns>
        EntitlementDetailResponseDto EntitlementsDelete(string id, int operationIndex = 0);

        /// <summary>
        /// Delete Entitlement
        /// </summary>
        /// <remarks>
        /// Delete an independent entitlement and unlink all mapped products.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EntitlementDetailResponseDto</returns>
        ApiResponse<EntitlementDetailResponseDto> EntitlementsDeleteWithHttpInfo(string id, int operationIndex = 0);
        /// <summary>
        /// Retrieve Entitlement
        /// </summary>
        /// <remarks>
        /// Retrieve a specific entitlement definition by ID.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EntitlementDetailResponseDto</returns>
        EntitlementDetailResponseDto EntitlementsGet(string id, int operationIndex = 0);

        /// <summary>
        /// Retrieve Entitlement
        /// </summary>
        /// <remarks>
        /// Retrieve a specific entitlement definition by ID.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EntitlementDetailResponseDto</returns>
        ApiResponse<EntitlementDetailResponseDto> EntitlementsGetWithHttpInfo(string id, int operationIndex = 0);
        /// <summary>
        /// List Entitlements
        /// </summary>
        /// <remarks>
        /// List all independent entitlements for the active business.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;EntitlementDetailResponseDto&gt;</returns>
        List<EntitlementDetailResponseDto> EntitlementsList(int operationIndex = 0);

        /// <summary>
        /// List Entitlements
        /// </summary>
        /// <remarks>
        /// List all independent entitlements for the active business.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;EntitlementDetailResponseDto&gt;</returns>
        ApiResponse<List<EntitlementDetailResponseDto>> EntitlementsListWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Update Entitlement
        /// </summary>
        /// <remarks>
        /// Update details of an existing independent entitlement.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="updateEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EntitlementDetailResponseDto</returns>
        EntitlementDetailResponseDto EntitlementsUpdate(string id, UpdateEntitlementDto updateEntitlementDto, int operationIndex = 0);

        /// <summary>
        /// Update Entitlement
        /// </summary>
        /// <remarks>
        /// Update details of an existing independent entitlement.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="updateEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EntitlementDetailResponseDto</returns>
        ApiResponse<EntitlementDetailResponseDto> EntitlementsUpdateWithHttpInfo(string id, UpdateEntitlementDto updateEntitlementDto, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEntitlementsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Entitlement
        /// </summary>
        /// <remarks>
        /// Create a new independent access entitlement.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EntitlementDetailResponseDto</returns>
        System.Threading.Tasks.Task<EntitlementDetailResponseDto> EntitlementsCreateAsync(CreateEntitlementDto createEntitlementDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Create Entitlement
        /// </summary>
        /// <remarks>
        /// Create a new independent access entitlement.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EntitlementDetailResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<EntitlementDetailResponseDto>> EntitlementsCreateWithHttpInfoAsync(CreateEntitlementDto createEntitlementDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Delete Entitlement
        /// </summary>
        /// <remarks>
        /// Delete an independent entitlement and unlink all mapped products.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EntitlementDetailResponseDto</returns>
        System.Threading.Tasks.Task<EntitlementDetailResponseDto> EntitlementsDeleteAsync(string id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Delete Entitlement
        /// </summary>
        /// <remarks>
        /// Delete an independent entitlement and unlink all mapped products.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EntitlementDetailResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<EntitlementDetailResponseDto>> EntitlementsDeleteWithHttpInfoAsync(string id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Retrieve Entitlement
        /// </summary>
        /// <remarks>
        /// Retrieve a specific entitlement definition by ID.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EntitlementDetailResponseDto</returns>
        System.Threading.Tasks.Task<EntitlementDetailResponseDto> EntitlementsGetAsync(string id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Retrieve Entitlement
        /// </summary>
        /// <remarks>
        /// Retrieve a specific entitlement definition by ID.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EntitlementDetailResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<EntitlementDetailResponseDto>> EntitlementsGetWithHttpInfoAsync(string id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// List Entitlements
        /// </summary>
        /// <remarks>
        /// List all independent entitlements for the active business.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;EntitlementDetailResponseDto&gt;</returns>
        System.Threading.Tasks.Task<List<EntitlementDetailResponseDto>> EntitlementsListAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// List Entitlements
        /// </summary>
        /// <remarks>
        /// List all independent entitlements for the active business.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;EntitlementDetailResponseDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<EntitlementDetailResponseDto>>> EntitlementsListWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Update Entitlement
        /// </summary>
        /// <remarks>
        /// Update details of an existing independent entitlement.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="updateEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EntitlementDetailResponseDto</returns>
        System.Threading.Tasks.Task<EntitlementDetailResponseDto> EntitlementsUpdateAsync(string id, UpdateEntitlementDto updateEntitlementDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Update Entitlement
        /// </summary>
        /// <remarks>
        /// Update details of an existing independent entitlement.
        /// </remarks>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="updateEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EntitlementDetailResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<EntitlementDetailResponseDto>> EntitlementsUpdateWithHttpInfoAsync(string id, UpdateEntitlementDto updateEntitlementDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEntitlementsApi : IEntitlementsApiSync, IEntitlementsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EntitlementsApi : IEntitlementsApi
    {
        private Solifyn.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EntitlementsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EntitlementsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EntitlementsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EntitlementsApi(string basePath)
        {
            this.Configuration = Solifyn.Client.Configuration.MergeConfigurations(
                Solifyn.Client.GlobalConfiguration.Instance,
                new Solifyn.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Solifyn.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Solifyn.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Solifyn.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EntitlementsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EntitlementsApi(Solifyn.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Solifyn.Client.Configuration.MergeConfigurations(
                Solifyn.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Solifyn.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Solifyn.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Solifyn.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EntitlementsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public EntitlementsApi(Solifyn.Client.ISynchronousClient client, Solifyn.Client.IAsynchronousClient asyncClient, Solifyn.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Solifyn.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Solifyn.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Solifyn.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Solifyn.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Solifyn.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Entitlement Create a new independent access entitlement.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EntitlementDetailResponseDto</returns>
        public EntitlementDetailResponseDto EntitlementsCreate(CreateEntitlementDto createEntitlementDto, int operationIndex = 0)
        {
            Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> localVarResponse = EntitlementsCreateWithHttpInfo(createEntitlementDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Entitlement Create a new independent access entitlement.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EntitlementDetailResponseDto</returns>
        public Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> EntitlementsCreateWithHttpInfo(CreateEntitlementDto createEntitlementDto, int operationIndex = 0)
        {
            // verify the required parameter 'createEntitlementDto' is set
            if (createEntitlementDto == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'createEntitlementDto' when calling EntitlementsApi->EntitlementsCreate");
            }

            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createEntitlementDto;

            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsCreate";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<EntitlementDetailResponseDto>("/v1/entitlements", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsCreate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Entitlement Create a new independent access entitlement.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EntitlementDetailResponseDto</returns>
        public async System.Threading.Tasks.Task<EntitlementDetailResponseDto> EntitlementsCreateAsync(CreateEntitlementDto createEntitlementDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> localVarResponse = await EntitlementsCreateWithHttpInfoAsync(createEntitlementDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Entitlement Create a new independent access entitlement.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EntitlementDetailResponseDto)</returns>
        public async System.Threading.Tasks.Task<Solifyn.Client.ApiResponse<EntitlementDetailResponseDto>> EntitlementsCreateWithHttpInfoAsync(CreateEntitlementDto createEntitlementDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'createEntitlementDto' is set
            if (createEntitlementDto == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'createEntitlementDto' when calling EntitlementsApi->EntitlementsCreate");
            }


            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createEntitlementDto;

            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsCreate";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<EntitlementDetailResponseDto>("/v1/entitlements", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsCreate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Entitlement Delete an independent entitlement and unlink all mapped products.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EntitlementDetailResponseDto</returns>
        public EntitlementDetailResponseDto EntitlementsDelete(string id, int operationIndex = 0)
        {
            Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> localVarResponse = EntitlementsDeleteWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Entitlement Delete an independent entitlement and unlink all mapped products.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EntitlementDetailResponseDto</returns>
        public Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> EntitlementsDeleteWithHttpInfo(string id, int operationIndex = 0)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'id' when calling EntitlementsApi->EntitlementsDelete");
            }

            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Solifyn.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsDelete";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Delete<EntitlementDetailResponseDto>("/v1/entitlements/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Entitlement Delete an independent entitlement and unlink all mapped products.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EntitlementDetailResponseDto</returns>
        public async System.Threading.Tasks.Task<EntitlementDetailResponseDto> EntitlementsDeleteAsync(string id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> localVarResponse = await EntitlementsDeleteWithHttpInfoAsync(id, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Entitlement Delete an independent entitlement and unlink all mapped products.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EntitlementDetailResponseDto)</returns>
        public async System.Threading.Tasks.Task<Solifyn.Client.ApiResponse<EntitlementDetailResponseDto>> EntitlementsDeleteWithHttpInfoAsync(string id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'id' when calling EntitlementsApi->EntitlementsDelete");
            }


            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Solifyn.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsDelete";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<EntitlementDetailResponseDto>("/v1/entitlements/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsDelete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve Entitlement Retrieve a specific entitlement definition by ID.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EntitlementDetailResponseDto</returns>
        public EntitlementDetailResponseDto EntitlementsGet(string id, int operationIndex = 0)
        {
            Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> localVarResponse = EntitlementsGetWithHttpInfo(id);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve Entitlement Retrieve a specific entitlement definition by ID.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EntitlementDetailResponseDto</returns>
        public Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> EntitlementsGetWithHttpInfo(string id, int operationIndex = 0)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'id' when calling EntitlementsApi->EntitlementsGet");
            }

            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Solifyn.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<EntitlementDetailResponseDto>("/v1/entitlements/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieve Entitlement Retrieve a specific entitlement definition by ID.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EntitlementDetailResponseDto</returns>
        public async System.Threading.Tasks.Task<EntitlementDetailResponseDto> EntitlementsGetAsync(string id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> localVarResponse = await EntitlementsGetWithHttpInfoAsync(id, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve Entitlement Retrieve a specific entitlement definition by ID.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EntitlementDetailResponseDto)</returns>
        public async System.Threading.Tasks.Task<Solifyn.Client.ApiResponse<EntitlementDetailResponseDto>> EntitlementsGetWithHttpInfoAsync(string id, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'id' when calling EntitlementsApi->EntitlementsGet");
            }


            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Solifyn.Client.ClientUtils.ParameterToString(id)); // path parameter

            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<EntitlementDetailResponseDto>("/v1/entitlements/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Entitlements List all independent entitlements for the active business.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;EntitlementDetailResponseDto&gt;</returns>
        public List<EntitlementDetailResponseDto> EntitlementsList(int operationIndex = 0)
        {
            Solifyn.Client.ApiResponse<List<EntitlementDetailResponseDto>> localVarResponse = EntitlementsListWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Entitlements List all independent entitlements for the active business.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;EntitlementDetailResponseDto&gt;</returns>
        public Solifyn.Client.ApiResponse<List<EntitlementDetailResponseDto>> EntitlementsListWithHttpInfo(int operationIndex = 0)
        {
            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsList";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<EntitlementDetailResponseDto>>("/v1/entitlements", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsList", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Entitlements List all independent entitlements for the active business.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;EntitlementDetailResponseDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<EntitlementDetailResponseDto>> EntitlementsListAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Solifyn.Client.ApiResponse<List<EntitlementDetailResponseDto>> localVarResponse = await EntitlementsListWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Entitlements List all independent entitlements for the active business.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;EntitlementDetailResponseDto&gt;)</returns>
        public async System.Threading.Tasks.Task<Solifyn.Client.ApiResponse<List<EntitlementDetailResponseDto>>> EntitlementsListWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsList";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<EntitlementDetailResponseDto>>("/v1/entitlements", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsList", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Entitlement Update details of an existing independent entitlement.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="updateEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EntitlementDetailResponseDto</returns>
        public EntitlementDetailResponseDto EntitlementsUpdate(string id, UpdateEntitlementDto updateEntitlementDto, int operationIndex = 0)
        {
            Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> localVarResponse = EntitlementsUpdateWithHttpInfo(id, updateEntitlementDto);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Entitlement Update details of an existing independent entitlement.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="updateEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EntitlementDetailResponseDto</returns>
        public Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> EntitlementsUpdateWithHttpInfo(string id, UpdateEntitlementDto updateEntitlementDto, int operationIndex = 0)
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'id' when calling EntitlementsApi->EntitlementsUpdate");
            }

            // verify the required parameter 'updateEntitlementDto' is set
            if (updateEntitlementDto == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'updateEntitlementDto' when calling EntitlementsApi->EntitlementsUpdate");
            }

            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Solifyn.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = updateEntitlementDto;

            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsUpdate";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Patch<EntitlementDetailResponseDto>("/v1/entitlements/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsUpdate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Entitlement Update details of an existing independent entitlement.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="updateEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EntitlementDetailResponseDto</returns>
        public async System.Threading.Tasks.Task<EntitlementDetailResponseDto> EntitlementsUpdateAsync(string id, UpdateEntitlementDto updateEntitlementDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Solifyn.Client.ApiResponse<EntitlementDetailResponseDto> localVarResponse = await EntitlementsUpdateWithHttpInfoAsync(id, updateEntitlementDto, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Entitlement Update details of an existing independent entitlement.
        /// </summary>
        /// <exception cref="Solifyn.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id">The unique entitlement ID.</param>
        /// <param name="updateEntitlementDto"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EntitlementDetailResponseDto)</returns>
        public async System.Threading.Tasks.Task<Solifyn.Client.ApiResponse<EntitlementDetailResponseDto>> EntitlementsUpdateWithHttpInfoAsync(string id, UpdateEntitlementDto updateEntitlementDto, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'id' is set
            if (id == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'id' when calling EntitlementsApi->EntitlementsUpdate");
            }

            // verify the required parameter 'updateEntitlementDto' is set
            if (updateEntitlementDto == null)
            {
                throw new Solifyn.Client.ApiException(400, "Missing required parameter 'updateEntitlementDto' when calling EntitlementsApi->EntitlementsUpdate");
            }


            Solifyn.Client.RequestOptions localVarRequestOptions = new Solifyn.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Solifyn.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Solifyn.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Solifyn.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.Data = updateEntitlementDto;

            localVarRequestOptions.Operation = "EntitlementsApi.EntitlementsUpdate";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<EntitlementDetailResponseDto>("/v1/entitlements/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EntitlementsUpdate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
