/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing BusinessFullCreateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BusinessFullCreateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BusinessFullCreateResponse
        //private BusinessFullCreateResponse instance;

        public BusinessFullCreateResponseTests()
        {
            // TODO uncomment below to create an instance of BusinessFullCreateResponse
            //instance = new BusinessFullCreateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BusinessFullCreateResponse
        /// </summary>
        [Fact]
        public void BusinessFullCreateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BusinessFullCreateResponse
            //Assert.IsType<BusinessFullCreateResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'BusinessId'
        /// </summary>
        [Fact]
        public void BusinessIdTest()
        {
            // TODO unit test for the property 'BusinessId'
        }
    }
}
