/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing BusinessCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BusinessCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BusinessCreate
        //private BusinessCreate instance;

        public BusinessCreateTests()
        {
            // TODO uncomment below to create an instance of BusinessCreate
            //instance = new BusinessCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BusinessCreate
        /// </summary>
        [Fact]
        public void BusinessCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" BusinessCreate
            //Assert.IsType<BusinessCreate>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
    }
}
