/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing CheckoutLinkResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckoutLinkResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckoutLinkResponseDto
        //private CheckoutLinkResponseDto instance;

        public CheckoutLinkResponseDtoTests()
        {
            // TODO uncomment below to create an instance of CheckoutLinkResponseDto
            //instance = new CheckoutLinkResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckoutLinkResponseDto
        /// </summary>
        [Fact]
        public void CheckoutLinkResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckoutLinkResponseDto
            //Assert.IsType<CheckoutLinkResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }

        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Fact]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }

        /// <summary>
        /// Test the property 'CustomerName'
        /// </summary>
        [Fact]
        public void CustomerNameTest()
        {
            // TODO unit test for the property 'CustomerName'
        }

        /// <summary>
        /// Test the property 'CustomerEmail'
        /// </summary>
        [Fact]
        public void CustomerEmailTest()
        {
            // TODO unit test for the property 'CustomerEmail'
        }

        /// <summary>
        /// Test the property 'AddressLine1'
        /// </summary>
        [Fact]
        public void AddressLine1Test()
        {
            // TODO unit test for the property 'AddressLine1'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

        /// <summary>
        /// Test the property 'RedirectUrl'
        /// </summary>
        [Fact]
        public void RedirectUrlTest()
        {
            // TODO unit test for the property 'RedirectUrl'
        }

        /// <summary>
        /// Test the property 'CancelUrl'
        /// </summary>
        [Fact]
        public void CancelUrlTest()
        {
            // TODO unit test for the property 'CancelUrl'
        }

        /// <summary>
        /// Test the property 'ShowDiscounts'
        /// </summary>
        [Fact]
        public void ShowDiscountsTest()
        {
            // TODO unit test for the property 'ShowDiscounts'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
