/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing CreateApiKeyDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateApiKeyDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateApiKeyDto
        //private CreateApiKeyDto instance;

        public CreateApiKeyDtoTests()
        {
            // TODO uncomment below to create an instance of CreateApiKeyDto
            //instance = new CreateApiKeyDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateApiKeyDto
        /// </summary>
        [Fact]
        public void CreateApiKeyDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateApiKeyDto
            //Assert.IsType<CreateApiKeyDto>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'AllowWrite'
        /// </summary>
        [Fact]
        public void AllowWriteTest()
        {
            // TODO unit test for the property 'AllowWrite'
        }
    }
}
