/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing DiscordRolesResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DiscordRolesResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DiscordRolesResponseDto
        //private DiscordRolesResponseDto instance;

        public DiscordRolesResponseDtoTests()
        {
            // TODO uncomment below to create an instance of DiscordRolesResponseDto
            //instance = new DiscordRolesResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiscordRolesResponseDto
        /// </summary>
        [Fact]
        public void DiscordRolesResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DiscordRolesResponseDto
            //Assert.IsType<DiscordRolesResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
    }
}
