/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing DisputeEvidenceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DisputeEvidenceDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DisputeEvidenceDto
        //private DisputeEvidenceDto instance;

        public DisputeEvidenceDtoTests()
        {
            // TODO uncomment below to create an instance of DisputeEvidenceDto
            //instance = new DisputeEvidenceDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DisputeEvidenceDto
        /// </summary>
        [Fact]
        public void DisputeEvidenceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DisputeEvidenceDto
            //Assert.IsType<DisputeEvidenceDto>(instance);
        }

        /// <summary>
        /// Test the property 'CancellationPolicy'
        /// </summary>
        [Fact]
        public void CancellationPolicyTest()
        {
            // TODO unit test for the property 'CancellationPolicy'
        }

        /// <summary>
        /// Test the property 'CustomerCommunication'
        /// </summary>
        [Fact]
        public void CustomerCommunicationTest()
        {
            // TODO unit test for the property 'CustomerCommunication'
        }

        /// <summary>
        /// Test the property 'RefundPolicy'
        /// </summary>
        [Fact]
        public void RefundPolicyTest()
        {
            // TODO unit test for the property 'RefundPolicy'
        }

        /// <summary>
        /// Test the property 'Uncategorized'
        /// </summary>
        [Fact]
        public void UncategorizedTest()
        {
            // TODO unit test for the property 'Uncategorized'
        }
    }
}
