/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing Dispute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DisputeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Dispute
        //private Dispute instance;

        public DisputeTests()
        {
            // TODO uncomment below to create an instance of Dispute
            //instance = new Dispute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Dispute
        /// </summary>
        [Fact]
        public void DisputeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Dispute
            //Assert.IsType<Dispute>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'WhopId'
        /// </summary>
        [Fact]
        public void WhopIdTest()
        {
            // TODO unit test for the property 'WhopId'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'Editable'
        /// </summary>
        [Fact]
        public void EditableTest()
        {
            // TODO unit test for the property 'Editable'
        }

        /// <summary>
        /// Test the property 'NeedsResponseBy'
        /// </summary>
        [Fact]
        public void NeedsResponseByTest()
        {
            // TODO unit test for the property 'NeedsResponseBy'
        }

        /// <summary>
        /// Test the property 'VisaRdr'
        /// </summary>
        [Fact]
        public void VisaRdrTest()
        {
            // TODO unit test for the property 'VisaRdr'
        }

        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Fact]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }

        /// <summary>
        /// Test the property 'CustomerName'
        /// </summary>
        [Fact]
        public void CustomerNameTest()
        {
            // TODO unit test for the property 'CustomerName'
        }

        /// <summary>
        /// Test the property 'CustomerEmail'
        /// </summary>
        [Fact]
        public void CustomerEmailTest()
        {
            // TODO unit test for the property 'CustomerEmail'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

        /// <summary>
        /// Test the property 'ProductDescription'
        /// </summary>
        [Fact]
        public void ProductDescriptionTest()
        {
            // TODO unit test for the property 'ProductDescription'
        }

        /// <summary>
        /// Test the property 'ServiceDate'
        /// </summary>
        [Fact]
        public void ServiceDateTest()
        {
            // TODO unit test for the property 'ServiceDate'
        }

        /// <summary>
        /// Test the property 'AccessActivityLog'
        /// </summary>
        [Fact]
        public void AccessActivityLogTest()
        {
            // TODO unit test for the property 'AccessActivityLog'
        }

        /// <summary>
        /// Test the property 'Evidence'
        /// </summary>
        [Fact]
        public void EvidenceTest()
        {
            // TODO unit test for the property 'Evidence'
        }

        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

        /// <summary>
        /// Test the property 'BusinessId'
        /// </summary>
        [Fact]
        public void BusinessIdTest()
        {
            // TODO unit test for the property 'BusinessId'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
