/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing LicensesActivateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LicensesActivateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LicensesActivateRequest
        //private LicensesActivateRequest instance;

        public LicensesActivateRequestTests()
        {
            // TODO uncomment below to create an instance of LicensesActivateRequest
            //instance = new LicensesActivateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LicensesActivateRequest
        /// </summary>
        [Fact]
        public void LicensesActivateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" LicensesActivateRequest
            //Assert.IsType<LicensesActivateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'DeviceIdentifier'
        /// </summary>
        [Fact]
        public void DeviceIdentifierTest()
        {
            // TODO unit test for the property 'DeviceIdentifier'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
