/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing MeterEventsResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MeterEventsResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MeterEventsResponseDto
        //private MeterEventsResponseDto instance;

        public MeterEventsResponseDtoTests()
        {
            // TODO uncomment below to create an instance of MeterEventsResponseDto
            //instance = new MeterEventsResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MeterEventsResponseDto
        /// </summary>
        [Fact]
        public void MeterEventsResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" MeterEventsResponseDto
            //Assert.IsType<MeterEventsResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'MeterId'
        /// </summary>
        [Fact]
        public void MeterIdTest()
        {
            // TODO unit test for the property 'MeterId'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
    }
}
