/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing OperationalWebhookEndpointUpdateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OperationalWebhookEndpointUpdateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OperationalWebhookEndpointUpdateDto
        //private OperationalWebhookEndpointUpdateDto instance;

        public OperationalWebhookEndpointUpdateDtoTests()
        {
            // TODO uncomment below to create an instance of OperationalWebhookEndpointUpdateDto
            //instance = new OperationalWebhookEndpointUpdateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OperationalWebhookEndpointUpdateDto
        /// </summary>
        [Fact]
        public void OperationalWebhookEndpointUpdateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OperationalWebhookEndpointUpdateDto
            //Assert.IsType<OperationalWebhookEndpointUpdateDto>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Fact]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }

        /// <summary>
        /// Test the property 'FilterTypes'
        /// </summary>
        [Fact]
        public void FilterTypesTest()
        {
            // TODO unit test for the property 'FilterTypes'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'ThrottleRate'
        /// </summary>
        [Fact]
        public void ThrottleRateTest()
        {
            // TODO unit test for the property 'ThrottleRate'
        }

        /// <summary>
        /// Test the property 'Uid'
        /// </summary>
        [Fact]
        public void UidTest()
        {
            // TODO unit test for the property 'Uid'
        }
    }
}
