/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing OperationalWebhookEndpointHeadersResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OperationalWebhookEndpointHeadersResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OperationalWebhookEndpointHeadersResponseDto
        //private OperationalWebhookEndpointHeadersResponseDto instance;

        public OperationalWebhookEndpointHeadersResponseDtoTests()
        {
            // TODO uncomment below to create an instance of OperationalWebhookEndpointHeadersResponseDto
            //instance = new OperationalWebhookEndpointHeadersResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OperationalWebhookEndpointHeadersResponseDto
        /// </summary>
        [Fact]
        public void OperationalWebhookEndpointHeadersResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OperationalWebhookEndpointHeadersResponseDto
            //Assert.IsType<OperationalWebhookEndpointHeadersResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Fact]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }

        /// <summary>
        /// Test the property 'Sensitive'
        /// </summary>
        [Fact]
        public void SensitiveTest()
        {
            // TODO unit test for the property 'Sensitive'
        }
    }
}
