/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing OrderBillingUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderBillingUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderBillingUpdate
        //private OrderBillingUpdate instance;

        public OrderBillingUpdateTests()
        {
            // TODO uncomment below to create an instance of OrderBillingUpdate
            //instance = new OrderBillingUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderBillingUpdate
        /// </summary>
        [Fact]
        public void OrderBillingUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderBillingUpdate
            //Assert.IsType<OrderBillingUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Fact]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Zipcode'
        /// </summary>
        [Fact]
        public void ZipcodeTest()
        {
            // TODO unit test for the property 'Zipcode'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
    }
}
