/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing PayoutAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayoutAccountTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayoutAccount
        //private PayoutAccount instance;

        public PayoutAccountTests()
        {
            // TODO uncomment below to create an instance of PayoutAccount
            //instance = new PayoutAccount();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayoutAccount
        /// </summary>
        [Fact]
        public void PayoutAccountInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayoutAccount
            //Assert.IsType<PayoutAccount>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Capabilities'
        /// </summary>
        [Fact]
        public void CapabilitiesTest()
        {
            // TODO unit test for the property 'Capabilities'
        }
    }
}
