/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing PricePreviewResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PricePreviewResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PricePreviewResponseDto
        //private PricePreviewResponseDto instance;

        public PricePreviewResponseDtoTests()
        {
            // TODO uncomment below to create an instance of PricePreviewResponseDto
            //instance = new PricePreviewResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PricePreviewResponseDto
        /// </summary>
        [Fact]
        public void PricePreviewResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PricePreviewResponseDto
            //Assert.IsType<PricePreviewResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'OriginalPrice'
        /// </summary>
        [Fact]
        public void OriginalPriceTest()
        {
            // TODO unit test for the property 'OriginalPrice'
        }

        /// <summary>
        /// Test the property 'OriginalCurrency'
        /// </summary>
        [Fact]
        public void OriginalCurrencyTest()
        {
            // TODO unit test for the property 'OriginalCurrency'
        }

        /// <summary>
        /// Test the property 'ConvertedPrice'
        /// </summary>
        [Fact]
        public void ConvertedPriceTest()
        {
            // TODO unit test for the property 'ConvertedPrice'
        }

        /// <summary>
        /// Test the property 'ConvertedCurrency'
        /// </summary>
        [Fact]
        public void ConvertedCurrencyTest()
        {
            // TODO unit test for the property 'ConvertedCurrency'
        }
    }
}
