/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing ProductsList200ResponsePagination
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductsList200ResponsePaginationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductsList200ResponsePagination
        //private ProductsList200ResponsePagination instance;

        public ProductsList200ResponsePaginationTests()
        {
            // TODO uncomment below to create an instance of ProductsList200ResponsePagination
            //instance = new ProductsList200ResponsePagination();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductsList200ResponsePagination
        /// </summary>
        [Fact]
        public void ProductsList200ResponsePaginationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductsList200ResponsePagination
            //Assert.IsType<ProductsList200ResponsePagination>(instance);
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'MaxPage'
        /// </summary>
        [Fact]
        public void MaxPageTest()
        {
            // TODO unit test for the property 'MaxPage'
        }
    }
}
