/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing SubscriptionAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubscriptionActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubscriptionAction
        //private SubscriptionAction instance;

        public SubscriptionActionTests()
        {
            // TODO uncomment below to create an instance of SubscriptionAction
            //instance = new SubscriptionAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubscriptionAction
        /// </summary>
        [Fact]
        public void SubscriptionActionInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubscriptionAction
            //Assert.IsType<SubscriptionAction>(instance);
        }

        /// <summary>
        /// Test the property 'FreeDays'
        /// </summary>
        [Fact]
        public void FreeDaysTest()
        {
            // TODO unit test for the property 'FreeDays'
        }

        /// <summary>
        /// Test the property 'CancellationMode'
        /// </summary>
        [Fact]
        public void CancellationModeTest()
        {
            // TODO unit test for the property 'CancellationMode'
        }

        /// <summary>
        /// Test the property 'VoidPayments'
        /// </summary>
        [Fact]
        public void VoidPaymentsTest()
        {
            // TODO unit test for the property 'VoidPayments'
        }

        /// <summary>
        /// Test the property 'AddonProductId'
        /// </summary>
        [Fact]
        public void AddonProductIdTest()
        {
            // TODO unit test for the property 'AddonProductId'
        }

        /// <summary>
        /// Test the property 'NewQuantity'
        /// </summary>
        [Fact]
        public void NewQuantityTest()
        {
            // TODO unit test for the property 'NewQuantity'
        }

        /// <summary>
        /// Test the property 'ProrationType'
        /// </summary>
        [Fact]
        public void ProrationTypeTest()
        {
            // TODO unit test for the property 'ProrationType'
        }

        /// <summary>
        /// Test the property 'IdempotencyKey'
        /// </summary>
        [Fact]
        public void IdempotencyKeyTest()
        {
            // TODO unit test for the property 'IdempotencyKey'
        }
    }
}
