/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing SubscriptionsAction201Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubscriptionsAction201ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubscriptionsAction201Response
        //private SubscriptionsAction201Response instance;

        public SubscriptionsAction201ResponseTests()
        {
            // TODO uncomment below to create an instance of SubscriptionsAction201Response
            //instance = new SubscriptionsAction201Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubscriptionsAction201Response
        /// </summary>
        [Fact]
        public void SubscriptionsAction201ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubscriptionsAction201Response
            //Assert.IsType<SubscriptionsAction201Response>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'JoinedAt'
        /// </summary>
        [Fact]
        public void JoinedAtTest()
        {
            // TODO unit test for the property 'JoinedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'ManageUrl'
        /// </summary>
        [Fact]
        public void ManageUrlTest()
        {
            // TODO unit test for the property 'ManageUrl'
        }

        /// <summary>
        /// Test the property 'Member'
        /// </summary>
        [Fact]
        public void MemberTest()
        {
            // TODO unit test for the property 'Member'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'RenewalPeriodStart'
        /// </summary>
        [Fact]
        public void RenewalPeriodStartTest()
        {
            // TODO unit test for the property 'RenewalPeriodStart'
        }

        /// <summary>
        /// Test the property 'RenewalPeriodEnd'
        /// </summary>
        [Fact]
        public void RenewalPeriodEndTest()
        {
            // TODO unit test for the property 'RenewalPeriodEnd'
        }

        /// <summary>
        /// Test the property 'CancelAtPeriodEnd'
        /// </summary>
        [Fact]
        public void CancelAtPeriodEndTest()
        {
            // TODO unit test for the property 'CancelAtPeriodEnd'
        }

        /// <summary>
        /// Test the property 'CancelOption'
        /// </summary>
        [Fact]
        public void CancelOptionTest()
        {
            // TODO unit test for the property 'CancelOption'
        }

        /// <summary>
        /// Test the property 'CancellationReason'
        /// </summary>
        [Fact]
        public void CancellationReasonTest()
        {
            // TODO unit test for the property 'CancellationReason'
        }

        /// <summary>
        /// Test the property 'CanceledAt'
        /// </summary>
        [Fact]
        public void CanceledAtTest()
        {
            // TODO unit test for the property 'CanceledAt'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }

        /// <summary>
        /// Test the property 'Plan'
        /// </summary>
        [Fact]
        public void PlanTest()
        {
            // TODO unit test for the property 'Plan'
        }

        /// <summary>
        /// Test the property 'PromoCode'
        /// </summary>
        [Fact]
        public void PromoCodeTest()
        {
            // TODO unit test for the property 'PromoCode'
        }

        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Fact]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }

        /// <summary>
        /// Test the property 'LicenseKey'
        /// </summary>
        [Fact]
        public void LicenseKeyTest()
        {
            // TODO unit test for the property 'LicenseKey'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'PaymentCollectionPaused'
        /// </summary>
        [Fact]
        public void PaymentCollectionPausedTest()
        {
            // TODO unit test for the property 'PaymentCollectionPaused'
        }

        /// <summary>
        /// Test the property 'CheckoutConfigurationId'
        /// </summary>
        [Fact]
        public void CheckoutConfigurationIdTest()
        {
            // TODO unit test for the property 'CheckoutConfigurationId'
        }

        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }

        /// <summary>
        /// Test the property 'AddonProductId'
        /// </summary>
        [Fact]
        public void AddonProductIdTest()
        {
            // TODO unit test for the property 'AddonProductId'
        }

        /// <summary>
        /// Test the property 'OldQuantity'
        /// </summary>
        [Fact]
        public void OldQuantityTest()
        {
            // TODO unit test for the property 'OldQuantity'
        }

        /// <summary>
        /// Test the property 'NewQuantity'
        /// </summary>
        [Fact]
        public void NewQuantityTest()
        {
            // TODO unit test for the property 'NewQuantity'
        }

        /// <summary>
        /// Test the property 'QuantityDelta'
        /// </summary>
        [Fact]
        public void QuantityDeltaTest()
        {
            // TODO unit test for the property 'QuantityDelta'
        }

        /// <summary>
        /// Test the property 'ProrationType'
        /// </summary>
        [Fact]
        public void ProrationTypeTest()
        {
            // TODO unit test for the property 'ProrationType'
        }

        /// <summary>
        /// Test the property 'CostImpact'
        /// </summary>
        [Fact]
        public void CostImpactTest()
        {
            // TODO unit test for the property 'CostImpact'
        }
    }
}
