/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing SupportedCurrenciesResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SupportedCurrenciesResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SupportedCurrenciesResponseDto
        //private SupportedCurrenciesResponseDto instance;

        public SupportedCurrenciesResponseDtoTests()
        {
            // TODO uncomment below to create an instance of SupportedCurrenciesResponseDto
            //instance = new SupportedCurrenciesResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SupportedCurrenciesResponseDto
        /// </summary>
        [Fact]
        public void SupportedCurrenciesResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SupportedCurrenciesResponseDto
            //Assert.IsType<SupportedCurrenciesResponseDto>(instance);
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
