/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateEntitlementDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateEntitlementDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateEntitlementDto
        //private UpdateEntitlementDto instance;

        public UpdateEntitlementDtoTests()
        {
            // TODO uncomment below to create an instance of UpdateEntitlementDto
            //instance = new UpdateEntitlementDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateEntitlementDto
        /// </summary>
        [Fact]
        public void UpdateEntitlementDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateEntitlementDto
            //Assert.IsType<UpdateEntitlementDto>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'GithubRepo'
        /// </summary>
        [Fact]
        public void GithubRepoTest()
        {
            // TODO unit test for the property 'GithubRepo'
        }

        /// <summary>
        /// Test the property 'GithubPermission'
        /// </summary>
        [Fact]
        public void GithubPermissionTest()
        {
            // TODO unit test for the property 'GithubPermission'
        }

        /// <summary>
        /// Test the property 'DiscordGuildId'
        /// </summary>
        [Fact]
        public void DiscordGuildIdTest()
        {
            // TODO unit test for the property 'DiscordGuildId'
        }

        /// <summary>
        /// Test the property 'DiscordRoleId'
        /// </summary>
        [Fact]
        public void DiscordRoleIdTest()
        {
            // TODO unit test for the property 'DiscordRoleId'
        }

        /// <summary>
        /// Test the property 'FramerTemplateId'
        /// </summary>
        [Fact]
        public void FramerTemplateIdTest()
        {
            // TODO unit test for the property 'FramerTemplateId'
        }

        /// <summary>
        /// Test the property 'LicenseKey'
        /// </summary>
        [Fact]
        public void LicenseKeyTest()
        {
            // TODO unit test for the property 'LicenseKey'
        }

        /// <summary>
        /// Test the property 'ActivationLimit'
        /// </summary>
        [Fact]
        public void ActivationLimitTest()
        {
            // TODO unit test for the property 'ActivationLimit'
        }

        /// <summary>
        /// Test the property 'ActivationMessage'
        /// </summary>
        [Fact]
        public void ActivationMessageTest()
        {
            // TODO unit test for the property 'ActivationMessage'
        }

        /// <summary>
        /// Test the property 'ExpiryHours'
        /// </summary>
        [Fact]
        public void ExpiryHoursTest()
        {
            // TODO unit test for the property 'ExpiryHours'
        }

        /// <summary>
        /// Test the property 'DigitalLink'
        /// </summary>
        [Fact]
        public void DigitalLinkTest()
        {
            // TODO unit test for the property 'DigitalLink'
        }

        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Fact]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
    }
}
