/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Solifyn.Model;
using Solifyn.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Solifyn.Test.Model
{
    /// <summary>
    ///  Class for testing UserSettingsUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserSettingsUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserSettingsUpdate
        //private UserSettingsUpdate instance;

        public UserSettingsUpdateTests()
        {
            // TODO uncomment below to create an instance of UserSettingsUpdate
            //instance = new UserSettingsUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserSettingsUpdate
        /// </summary>
        [Fact]
        public void UserSettingsUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserSettingsUpdate
            //Assert.IsType<UserSettingsUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'Subdomain'
        /// </summary>
        [Fact]
        public void SubdomainTest()
        {
            // TODO unit test for the property 'Subdomain'
        }

        /// <summary>
        /// Test the property 'StoreName'
        /// </summary>
        [Fact]
        public void StoreNameTest()
        {
            // TODO unit test for the property 'StoreName'
        }

        /// <summary>
        /// Test the property 'SocialLinks'
        /// </summary>
        [Fact]
        public void SocialLinksTest()
        {
            // TODO unit test for the property 'SocialLinks'
        }

        /// <summary>
        /// Test the property 'PageTitle'
        /// </summary>
        [Fact]
        public void PageTitleTest()
        {
            // TODO unit test for the property 'PageTitle'
        }

        /// <summary>
        /// Test the property 'SeoDescription'
        /// </summary>
        [Fact]
        public void SeoDescriptionTest()
        {
            // TODO unit test for the property 'SeoDescription'
        }

        /// <summary>
        /// Test the property 'SeoImage'
        /// </summary>
        [Fact]
        public void SeoImageTest()
        {
            // TODO unit test for the property 'SeoImage'
        }

        /// <summary>
        /// Test the property 'FaviconUrl'
        /// </summary>
        [Fact]
        public void FaviconUrlTest()
        {
            // TODO unit test for the property 'FaviconUrl'
        }

        /// <summary>
        /// Test the property 'GoogleAnalyticsId'
        /// </summary>
        [Fact]
        public void GoogleAnalyticsIdTest()
        {
            // TODO unit test for the property 'GoogleAnalyticsId'
        }

        /// <summary>
        /// Test the property 'GoogleTagManagerId'
        /// </summary>
        [Fact]
        public void GoogleTagManagerIdTest()
        {
            // TODO unit test for the property 'GoogleTagManagerId'
        }

        /// <summary>
        /// Test the property 'MetaPixelId'
        /// </summary>
        [Fact]
        public void MetaPixelIdTest()
        {
            // TODO unit test for the property 'MetaPixelId'
        }

        /// <summary>
        /// Test the property 'LogoUrl'
        /// </summary>
        [Fact]
        public void LogoUrlTest()
        {
            // TODO unit test for the property 'LogoUrl'
        }

        /// <summary>
        /// Test the property 'BusinessTitle'
        /// </summary>
        [Fact]
        public void BusinessTitleTest()
        {
            // TODO unit test for the property 'BusinessTitle'
        }

        /// <summary>
        /// Test the property 'StatementDescriptor'
        /// </summary>
        [Fact]
        public void StatementDescriptorTest()
        {
            // TODO unit test for the property 'StatementDescriptor'
        }

        /// <summary>
        /// Test the property 'DefaultCurrency'
        /// </summary>
        [Fact]
        public void DefaultCurrencyTest()
        {
            // TODO unit test for the property 'DefaultCurrency'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'AvatarUrl'
        /// </summary>
        [Fact]
        public void AvatarUrlTest()
        {
            // TODO unit test for the property 'AvatarUrl'
        }

        /// <summary>
        /// Test the property 'PayoutThreshold'
        /// </summary>
        [Fact]
        public void PayoutThresholdTest()
        {
            // TODO unit test for the property 'PayoutThreshold'
        }

        /// <summary>
        /// Test the property 'NotifyOnSuccess'
        /// </summary>
        [Fact]
        public void NotifyOnSuccessTest()
        {
            // TODO unit test for the property 'NotifyOnSuccess'
        }

        /// <summary>
        /// Test the property 'SendLicenseKeyEmail'
        /// </summary>
        [Fact]
        public void SendLicenseKeyEmailTest()
        {
            // TODO unit test for the property 'SendLicenseKeyEmail'
        }

        /// <summary>
        /// Test the property 'SendDigitalFileEmail'
        /// </summary>
        [Fact]
        public void SendDigitalFileEmailTest()
        {
            // TODO unit test for the property 'SendDigitalFileEmail'
        }

        /// <summary>
        /// Test the property 'NotifyOnSubscriptionPlanChanged'
        /// </summary>
        [Fact]
        public void NotifyOnSubscriptionPlanChangedTest()
        {
            // TODO unit test for the property 'NotifyOnSubscriptionPlanChanged'
        }

        /// <summary>
        /// Test the property 'NotifyOnSubscriptionSetToCancel'
        /// </summary>
        [Fact]
        public void NotifyOnSubscriptionSetToCancelTest()
        {
            // TODO unit test for the property 'NotifyOnSubscriptionSetToCancel'
        }

        /// <summary>
        /// Test the property 'NotifyOnSubscriptionCancelled'
        /// </summary>
        [Fact]
        public void NotifyOnSubscriptionCancelledTest()
        {
            // TODO unit test for the property 'NotifyOnSubscriptionCancelled'
        }

        /// <summary>
        /// Test the property 'NotifyOnRefundSuccessful'
        /// </summary>
        [Fact]
        public void NotifyOnRefundSuccessfulTest()
        {
            // TODO unit test for the property 'NotifyOnRefundSuccessful'
        }

        /// <summary>
        /// Test the property 'NotifyOnPaymentFailed'
        /// </summary>
        [Fact]
        public void NotifyOnPaymentFailedTest()
        {
            // TODO unit test for the property 'NotifyOnPaymentFailed'
        }

        /// <summary>
        /// Test the property 'NotifyOnSubscriptionRenewalFailed'
        /// </summary>
        [Fact]
        public void NotifyOnSubscriptionRenewalFailedTest()
        {
            // TODO unit test for the property 'NotifyOnSubscriptionRenewalFailed'
        }

        /// <summary>
        /// Test the property 'NotifyOnSubscriptionTrialEnding'
        /// </summary>
        [Fact]
        public void NotifyOnSubscriptionTrialEndingTest()
        {
            // TODO unit test for the property 'NotifyOnSubscriptionTrialEnding'
        }

        /// <summary>
        /// Test the property 'NotifyOnSubscriptionPaused'
        /// </summary>
        [Fact]
        public void NotifyOnSubscriptionPausedTest()
        {
            // TODO unit test for the property 'NotifyOnSubscriptionPaused'
        }
    }
}
