/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// AddCollectionProductsDto
    /// </summary>
    [DataContract(Name = "AddCollectionProductsDto")]
    public partial class AddCollectionProductsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddCollectionProductsDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddCollectionProductsDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddCollectionProductsDto" /> class.
        /// </summary>
        /// <param name="products">List of products to add or update in the collection. (required).</param>
        public AddCollectionProductsDto(List<CollectionProductEntry> products = default(List<CollectionProductEntry>))
        {
            // to ensure "products" is required (not null)
            if (products == null)
            {
                throw new ArgumentNullException("products is a required property for AddCollectionProductsDto and cannot be null");
            }
            this.Products = products;
        }

        /// <summary>
        /// List of products to add or update in the collection.
        /// </summary>
        /// <value>List of products to add or update in the collection.</value>
        [DataMember(Name = "products", IsRequired = true, EmitDefaultValue = true)]
        public List<CollectionProductEntry> Products { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddCollectionProductsDto {\n");
            sb.Append("  Products: ").Append(Products).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
