/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// AddonCreate
    /// </summary>
    [DataContract(Name = "AddonCreate")]
    public partial class AddonCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddonCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddonCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddonCreate" /> class.
        /// </summary>
        /// <param name="productId">The product ID of the addon product. (required).</param>
        /// <param name="minQuantity">Minimum quantity of the addon allowed to be purchased. (required) (default to 0M).</param>
        /// <param name="maxQuantity">Maximum quantity of the addon allowed to be purchased (optional)..</param>
        /// <param name="priceOverride">Price override for the addon product when purchased with this parent (optional)..</param>
        /// <param name="isSeatAddon">Flag indicating if this addon represents a seat/license limit increment. (required) (default to false).</param>
        public AddonCreate(string productId = default(string), decimal minQuantity = 0M, decimal maxQuantity = default(decimal), decimal priceOverride = default(decimal), bool isSeatAddon = false)
        {
            // to ensure "productId" is required (not null)
            if (productId == null)
            {
                throw new ArgumentNullException("productId is a required property for AddonCreate and cannot be null");
            }
            this.ProductId = productId;
            this.MinQuantity = minQuantity;
            this.IsSeatAddon = isSeatAddon;
            this.MaxQuantity = maxQuantity;
            this.PriceOverride = priceOverride;
        }

        /// <summary>
        /// The product ID of the addon product.
        /// </summary>
        /// <value>The product ID of the addon product.</value>
        /*
        <example>prod_addon_123</example>
        */
        [DataMember(Name = "productId", IsRequired = true, EmitDefaultValue = true)]
        public string ProductId { get; set; }

        /// <summary>
        /// Minimum quantity of the addon allowed to be purchased.
        /// </summary>
        /// <value>Minimum quantity of the addon allowed to be purchased.</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "minQuantity", IsRequired = true, EmitDefaultValue = true)]
        public decimal MinQuantity { get; set; }

        /// <summary>
        /// Maximum quantity of the addon allowed to be purchased (optional).
        /// </summary>
        /// <value>Maximum quantity of the addon allowed to be purchased (optional).</value>
        /*
        <example>10</example>
        */
        [DataMember(Name = "maxQuantity", EmitDefaultValue = false)]
        public decimal MaxQuantity { get; set; }

        /// <summary>
        /// Price override for the addon product when purchased with this parent (optional).
        /// </summary>
        /// <value>Price override for the addon product when purchased with this parent (optional).</value>
        /*
        <example>15</example>
        */
        [DataMember(Name = "priceOverride", EmitDefaultValue = false)]
        public decimal PriceOverride { get; set; }

        /// <summary>
        /// Flag indicating if this addon represents a seat/license limit increment.
        /// </summary>
        /// <value>Flag indicating if this addon represents a seat/license limit increment.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isSeatAddon", IsRequired = true, EmitDefaultValue = true)]
        public bool IsSeatAddon { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddonCreate {\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  MinQuantity: ").Append(MinQuantity).Append("\n");
            sb.Append("  MaxQuantity: ").Append(MaxQuantity).Append("\n");
            sb.Append("  PriceOverride: ").Append(PriceOverride).Append("\n");
            sb.Append("  IsSeatAddon: ").Append(IsSeatAddon).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
