/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// CheckoutSessionDetailsDto
    /// </summary>
    [DataContract(Name = "CheckoutSessionDetailsDto")]
    public partial class CheckoutSessionDetailsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutSessionDetailsDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CheckoutSessionDetailsDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckoutSessionDetailsDto" /> class.
        /// </summary>
        /// <param name="id">Checkout session identifier (required).</param>
        /// <param name="price">Total purchase amount (required).</param>
        /// <param name="currency">ISO currency code of the purchase (required).</param>
        /// <param name="storeName">Title or name of the merchant/store selling the item (required).</param>
        /// <param name="status">Current status of the checkout session (required).</param>
        /// <param name="billingAddress">Customer billing address details.</param>
        /// <param name="customFields">Custom fields collected during purchase.</param>
        /// <param name="sessionId">The payment partner session ID.</param>
        /// <param name="paymentId">Database payment transaction ID.</param>
        /// <param name="checkoutUrl">Checkout session redirect URL if loaded in link mode.</param>
        /// <param name="product">The details of the product being purchased.</param>
        /// <param name="entitlementGrants">List of entitlement grants (e.g. GitHub repo invites) associated with this checkout..</param>
        public CheckoutSessionDetailsDto(string id = default(string), decimal price = default(decimal), string currency = default(string), string storeName = default(string), string status = default(string), Object billingAddress = default(Object), Object customFields = default(Object), string sessionId = default(string), string paymentId = default(string), string checkoutUrl = default(string), Product product = default(Product), List<Object> entitlementGrants = default(List<Object>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for CheckoutSessionDetailsDto and cannot be null");
            }
            this.Id = id;
            this.Price = price;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for CheckoutSessionDetailsDto and cannot be null");
            }
            this.Currency = currency;
            // to ensure "storeName" is required (not null)
            if (storeName == null)
            {
                throw new ArgumentNullException("storeName is a required property for CheckoutSessionDetailsDto and cannot be null");
            }
            this.StoreName = storeName;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for CheckoutSessionDetailsDto and cannot be null");
            }
            this.Status = status;
            this.BillingAddress = billingAddress;
            this.CustomFields = customFields;
            this.SessionId = sessionId;
            this.PaymentId = paymentId;
            this.CheckoutUrl = checkoutUrl;
            this.Product = product;
            this.EntitlementGrants = entitlementGrants;
        }

        /// <summary>
        /// Checkout session identifier
        /// </summary>
        /// <value>Checkout session identifier</value>
        /*
        <example>ch_XXXXXXXXXXX</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Total purchase amount
        /// </summary>
        /// <value>Total purchase amount</value>
        /*
        <example>10</example>
        */
        [DataMember(Name = "price", IsRequired = true, EmitDefaultValue = true)]
        public decimal Price { get; set; }

        /// <summary>
        /// ISO currency code of the purchase
        /// </summary>
        /// <value>ISO currency code of the purchase</value>
        /*
        <example>USD</example>
        */
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Title or name of the merchant/store selling the item
        /// </summary>
        /// <value>Title or name of the merchant/store selling the item</value>
        /*
        <example>Official Store</example>
        */
        [DataMember(Name = "storeName", IsRequired = true, EmitDefaultValue = true)]
        public string StoreName { get; set; }

        /// <summary>
        /// Current status of the checkout session
        /// </summary>
        /// <value>Current status of the checkout session</value>
        /*
        <example>pending</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Customer billing address details
        /// </summary>
        /// <value>Customer billing address details</value>
        [DataMember(Name = "billingAddress", EmitDefaultValue = false)]
        public Object BillingAddress { get; set; }

        /// <summary>
        /// Custom fields collected during purchase
        /// </summary>
        /// <value>Custom fields collected during purchase</value>
        [DataMember(Name = "customFields", EmitDefaultValue = false)]
        public Object CustomFields { get; set; }

        /// <summary>
        /// The payment partner session ID
        /// </summary>
        /// <value>The payment partner session ID</value>
        /*
        <example>ch_XXXXXXXXX</example>
        */
        [DataMember(Name = "session_id", EmitDefaultValue = false)]
        public string SessionId { get; set; }

        /// <summary>
        /// Database payment transaction ID
        /// </summary>
        /// <value>Database payment transaction ID</value>
        /*
        <example>pay_XXXXXXXXX</example>
        */
        [DataMember(Name = "paymentId", EmitDefaultValue = false)]
        public string PaymentId { get; set; }

        /// <summary>
        /// Checkout session redirect URL if loaded in link mode
        /// </summary>
        /// <value>Checkout session redirect URL if loaded in link mode</value>
        /*
        <example>https://solifyn.com/checkout/prod_XXXXXXXXX?checkout_id&#x3D;019e56ba-9832-72ae-XXXXXXXXXXX</example>
        */
        [DataMember(Name = "checkoutUrl", EmitDefaultValue = false)]
        public string CheckoutUrl { get; set; }

        /// <summary>
        /// The details of the product being purchased
        /// </summary>
        /// <value>The details of the product being purchased</value>
        [DataMember(Name = "product", EmitDefaultValue = true)]
        public Product Product { get; set; }

        /// <summary>
        /// List of entitlement grants (e.g. GitHub repo invites) associated with this checkout.
        /// </summary>
        /// <value>List of entitlement grants (e.g. GitHub repo invites) associated with this checkout.</value>
        [DataMember(Name = "entitlementGrants", EmitDefaultValue = false)]
        public List<Object> EntitlementGrants { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckoutSessionDetailsDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  StoreName: ").Append(StoreName).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  BillingAddress: ").Append(BillingAddress).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  PaymentId: ").Append(PaymentId).Append("\n");
            sb.Append("  CheckoutUrl: ").Append(CheckoutUrl).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  EntitlementGrants: ").Append(EntitlementGrants).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
