/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// CollectionArchivedResponseDto
    /// </summary>
    [DataContract(Name = "CollectionArchivedResponseDto")]
    public partial class CollectionArchivedResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionArchivedResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CollectionArchivedResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CollectionArchivedResponseDto" /> class.
        /// </summary>
        /// <param name="message">Response message indicating the outcome of the action. (required).</param>
        public CollectionArchivedResponseDto(string message = default(string))
        {
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for CollectionArchivedResponseDto and cannot be null");
            }
            this.Message = message;
        }

        /// <summary>
        /// Response message indicating the outcome of the action.
        /// </summary>
        /// <value>Response message indicating the outcome of the action.</value>
        /*
        <example>Collection archived successfully</example>
        */
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CollectionArchivedResponseDto {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
