/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// CreateFramerTemplateDto
    /// </summary>
    [DataContract(Name = "CreateFramerTemplateDto")]
    public partial class CreateFramerTemplateDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateFramerTemplateDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateFramerTemplateDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateFramerTemplateDto" /> class.
        /// </summary>
        /// <param name="name">The name of the Framer template. (required).</param>
        /// <param name="remixLink">The public Framer remix link. (required).</param>
        /// <param name="description">A brief description of the template..</param>
        public CreateFramerTemplateDto(string name = default(string), string remixLink = default(string), string description = default(string))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateFramerTemplateDto and cannot be null");
            }
            this.Name = name;
            // to ensure "remixLink" is required (not null)
            if (remixLink == null)
            {
                throw new ArgumentNullException("remixLink is a required property for CreateFramerTemplateDto and cannot be null");
            }
            this.RemixLink = remixLink;
            this.Description = description;
        }

        /// <summary>
        /// The name of the Framer template.
        /// </summary>
        /// <value>The name of the Framer template.</value>
        /*
        <example>Portfolio Template</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The public Framer remix link.
        /// </summary>
        /// <value>The public Framer remix link.</value>
        /*
        <example>https://framer.com/projects/xyz</example>
        */
        [DataMember(Name = "remixLink", IsRequired = true, EmitDefaultValue = true)]
        public string RemixLink { get; set; }

        /// <summary>
        /// A brief description of the template.
        /// </summary>
        /// <value>A brief description of the template.</value>
        /*
        <example>Premium dark-mode portfolio.</example>
        */
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateFramerTemplateDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RemixLink: ").Append(RemixLink).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
