/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// CreateCollectionCheckoutDto
    /// </summary>
    [DataContract(Name = "CreateCollectionCheckoutDto")]
    public partial class CreateCollectionCheckoutDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCollectionCheckoutDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateCollectionCheckoutDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCollectionCheckoutDto" /> class.
        /// </summary>
        /// <param name="collectionId">The database ID of the collection to checkout (required).</param>
        /// <param name="quantity">Quantity of collections to buy (default to 1M).</param>
        /// <param name="discountCode">Discount code to apply.</param>
        /// <param name="aff">Affiliate tracking code.</param>
        /// <param name="customFields">Custom text fields / selected addons.</param>
        public CreateCollectionCheckoutDto(string collectionId = default(string), decimal quantity = 1M, string discountCode = default(string), string aff = default(string), Object customFields = default(Object))
        {
            // to ensure "collectionId" is required (not null)
            if (collectionId == null)
            {
                throw new ArgumentNullException("collectionId is a required property for CreateCollectionCheckoutDto and cannot be null");
            }
            this.CollectionId = collectionId;
            this.Quantity = quantity;
            this.DiscountCode = discountCode;
            this.Aff = aff;
            this.CustomFields = customFields;
        }

        /// <summary>
        /// The database ID of the collection to checkout
        /// </summary>
        /// <value>The database ID of the collection to checkout</value>
        /*
        <example>col_123</example>
        */
        [DataMember(Name = "collectionId", IsRequired = true, EmitDefaultValue = true)]
        public string CollectionId { get; set; }

        /// <summary>
        /// Quantity of collections to buy
        /// </summary>
        /// <value>Quantity of collections to buy</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "quantity", EmitDefaultValue = false)]
        public decimal Quantity { get; set; }

        /// <summary>
        /// Discount code to apply
        /// </summary>
        /// <value>Discount code to apply</value>
        /*
        <example>PROMO10</example>
        */
        [DataMember(Name = "discountCode", EmitDefaultValue = false)]
        public string DiscountCode { get; set; }

        /// <summary>
        /// Affiliate tracking code
        /// </summary>
        /// <value>Affiliate tracking code</value>
        /*
        <example>partner_abc</example>
        */
        [DataMember(Name = "aff", EmitDefaultValue = false)]
        public string Aff { get; set; }

        /// <summary>
        /// Custom text fields / selected addons
        /// </summary>
        /// <value>Custom text fields / selected addons</value>
        [DataMember(Name = "customFields", EmitDefaultValue = false)]
        public Object CustomFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateCollectionCheckoutDto {\n");
            sb.Append("  CollectionId: ").Append(CollectionId).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  DiscountCode: ").Append(DiscountCode).Append("\n");
            sb.Append("  Aff: ").Append(Aff).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
