/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// DiscountsList200ResponsePagination
    /// </summary>
    [DataContract(Name = "discounts_list_200_response_pagination")]
    public partial class DiscountsList200ResponsePagination : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DiscountsList200ResponsePagination" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DiscountsList200ResponsePagination() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DiscountsList200ResponsePagination" /> class.
        /// </summary>
        /// <param name="total">Total number of items matching filters. (required).</param>
        /// <param name="totalCount">Total number of items matching filters (alias). (required).</param>
        /// <param name="maxPage">Maximum page index available based on current page size. (required).</param>
        public DiscountsList200ResponsePagination(int total = default(int), int totalCount = default(int), int maxPage = default(int))
        {
            this.Total = total;
            this.TotalCount = totalCount;
            this.MaxPage = maxPage;
        }

        /// <summary>
        /// Total number of items matching filters.
        /// </summary>
        /// <value>Total number of items matching filters.</value>
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public int Total { get; set; }

        /// <summary>
        /// Total number of items matching filters (alias).
        /// </summary>
        /// <value>Total number of items matching filters (alias).</value>
        [DataMember(Name = "total_count", IsRequired = true, EmitDefaultValue = true)]
        public int TotalCount { get; set; }

        /// <summary>
        /// Maximum page index available based on current page size.
        /// </summary>
        /// <value>Maximum page index available based on current page size.</value>
        [DataMember(Name = "max_page", IsRequired = true, EmitDefaultValue = true)]
        public int MaxPage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DiscountsList200ResponsePagination {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  MaxPage: ").Append(MaxPage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
