/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// DisputeEvidenceDto
    /// </summary>
    [DataContract(Name = "DisputeEvidenceDto")]
    public partial class DisputeEvidenceDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DisputeEvidenceDto" /> class.
        /// </summary>
        /// <param name="cancellationPolicy">Cancellation policy attachment ID.</param>
        /// <param name="customerCommunication">Customer communication attachment ID.</param>
        /// <param name="refundPolicy">Refund policy attachment ID.</param>
        /// <param name="uncategorized">Uncategorized attachment ID.</param>
        public DisputeEvidenceDto(string cancellationPolicy = default(string), string customerCommunication = default(string), string refundPolicy = default(string), string uncategorized = default(string))
        {
            this.CancellationPolicy = cancellationPolicy;
            this.CustomerCommunication = customerCommunication;
            this.RefundPolicy = refundPolicy;
            this.Uncategorized = uncategorized;
        }

        /// <summary>
        /// Cancellation policy attachment ID
        /// </summary>
        /// <value>Cancellation policy attachment ID</value>
        /*
        <example>file_123</example>
        */
        [DataMember(Name = "cancellation_policy", EmitDefaultValue = true)]
        public string CancellationPolicy { get; set; }

        /// <summary>
        /// Customer communication attachment ID
        /// </summary>
        /// <value>Customer communication attachment ID</value>
        /*
        <example>file_456</example>
        */
        [DataMember(Name = "customer_communication", EmitDefaultValue = true)]
        public string CustomerCommunication { get; set; }

        /// <summary>
        /// Refund policy attachment ID
        /// </summary>
        /// <value>Refund policy attachment ID</value>
        /*
        <example>file_789</example>
        */
        [DataMember(Name = "refund_policy", EmitDefaultValue = true)]
        public string RefundPolicy { get; set; }

        /// <summary>
        /// Uncategorized attachment ID
        /// </summary>
        /// <value>Uncategorized attachment ID</value>
        /*
        <example>file_000</example>
        */
        [DataMember(Name = "uncategorized", EmitDefaultValue = true)]
        public string Uncategorized { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DisputeEvidenceDto {\n");
            sb.Append("  CancellationPolicy: ").Append(CancellationPolicy).Append("\n");
            sb.Append("  CustomerCommunication: ").Append(CustomerCommunication).Append("\n");
            sb.Append("  RefundPolicy: ").Append(RefundPolicy).Append("\n");
            sb.Append("  Uncategorized: ").Append(Uncategorized).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
