/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// DisputeAttachmentDto
    /// </summary>
    [DataContract(Name = "DisputeAttachmentDto")]
    public partial class DisputeAttachmentDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DisputeAttachmentDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DisputeAttachmentDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DisputeAttachmentDto" /> class.
        /// </summary>
        /// <param name="id">The uploaded file ID from the file service (required).</param>
        public DisputeAttachmentDto(string id = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for DisputeAttachmentDto and cannot be null");
            }
            this.Id = id;
        }

        /// <summary>
        /// The uploaded file ID from the file service
        /// </summary>
        /// <value>The uploaded file ID from the file service</value>
        /*
        <example>file_123</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DisputeAttachmentDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
