/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// DisputeListMetaDto
    /// </summary>
    [DataContract(Name = "DisputeListMetaDto")]
    public partial class DisputeListMetaDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DisputeListMetaDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DisputeListMetaDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DisputeListMetaDto" /> class.
        /// </summary>
        /// <param name="total">Total count of disputes (required).</param>
        /// <param name="page">Current page number (required).</param>
        /// <param name="limit">Limit of items per page (required).</param>
        /// <param name="totalPages">Total number of pages (required).</param>
        public DisputeListMetaDto(decimal total = default(decimal), decimal page = default(decimal), decimal limit = default(decimal), decimal totalPages = default(decimal))
        {
            this.Total = total;
            this.Page = page;
            this.Limit = limit;
            this.TotalPages = totalPages;
        }

        /// <summary>
        /// Total count of disputes
        /// </summary>
        /// <value>Total count of disputes</value>
        /*
        <example>10</example>
        */
        [DataMember(Name = "total", IsRequired = true, EmitDefaultValue = true)]
        public decimal Total { get; set; }

        /// <summary>
        /// Current page number
        /// </summary>
        /// <value>Current page number</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "page", IsRequired = true, EmitDefaultValue = true)]
        public decimal Page { get; set; }

        /// <summary>
        /// Limit of items per page
        /// </summary>
        /// <value>Limit of items per page</value>
        /*
        <example>10</example>
        */
        [DataMember(Name = "limit", IsRequired = true, EmitDefaultValue = true)]
        public decimal Limit { get; set; }

        /// <summary>
        /// Total number of pages
        /// </summary>
        /// <value>Total number of pages</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "totalPages", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalPages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DisputeListMetaDto {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  TotalPages: ").Append(TotalPages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
