/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// LicensesUpdateInstancePostRequest
    /// </summary>
    [DataContract(Name = "licenses_updateInstancePost_request")]
    public partial class LicensesUpdateInstancePostRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LicensesUpdateInstancePostRequest" /> class.
        /// </summary>
        /// <param name="instanceName">A new human-readable display name for this instance..</param>
        /// <param name="ipAddress">A new IP address to record for this instance..</param>
        public LicensesUpdateInstancePostRequest(string instanceName = default(string), string ipAddress = default(string))
        {
            this.InstanceName = instanceName;
            this.IpAddress = ipAddress;
        }

        /// <summary>
        /// A new human-readable display name for this instance.
        /// </summary>
        /// <value>A new human-readable display name for this instance.</value>
        /*
        <example>MacBook Pro 16&quot;</example>
        */
        [DataMember(Name = "instanceName", EmitDefaultValue = false)]
        public string InstanceName { get; set; }

        /// <summary>
        /// A new IP address to record for this instance.
        /// </summary>
        /// <value>A new IP address to record for this instance.</value>
        /*
        <example>203.0.113.42</example>
        */
        [DataMember(Name = "ipAddress", EmitDefaultValue = false)]
        public string IpAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LicensesUpdateInstancePostRequest {\n");
            sb.Append("  InstanceName: ").Append(InstanceName).Append("\n");
            sb.Append("  IpAddress: ").Append(IpAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
