/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// LicensesActivateRequest
    /// </summary>
    [DataContract(Name = "licenses_activate_request")]
    public partial class LicensesActivateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LicensesActivateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LicensesActivateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LicensesActivateRequest" /> class.
        /// </summary>
        /// <param name="key">The license key. (required).</param>
        /// <param name="deviceIdentifier">Unique identifier of the device/machine being activated. (required).</param>
        /// <param name="name">A user-friendly label/name for the instance. (required).</param>
        public LicensesActivateRequest(string key = default(string), string deviceIdentifier = default(string), string name = default(string))
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for LicensesActivateRequest and cannot be null");
            }
            this.Key = key;
            // to ensure "deviceIdentifier" is required (not null)
            if (deviceIdentifier == null)
            {
                throw new ArgumentNullException("deviceIdentifier is a required property for LicensesActivateRequest and cannot be null");
            }
            this.DeviceIdentifier = deviceIdentifier;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for LicensesActivateRequest and cannot be null");
            }
            this.Name = name;
        }

        /// <summary>
        /// The license key.
        /// </summary>
        /// <value>The license key.</value>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Unique identifier of the device/machine being activated.
        /// </summary>
        /// <value>Unique identifier of the device/machine being activated.</value>
        [DataMember(Name = "deviceIdentifier", IsRequired = true, EmitDefaultValue = true)]
        public string DeviceIdentifier { get; set; }

        /// <summary>
        /// A user-friendly label/name for the instance.
        /// </summary>
        /// <value>A user-friendly label/name for the instance.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LicensesActivateRequest {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  DeviceIdentifier: ").Append(DeviceIdentifier).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
