/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// LicenseSubDto
    /// </summary>
    [DataContract(Name = "LicenseSubDto")]
    public partial class LicenseSubDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LicenseSubDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LicenseSubDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LicenseSubDto" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="key">key (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="activationLimit">activationLimit (required).</param>
        /// <param name="activationMessage">activationMessage (required).</param>
        /// <param name="expiresAt">expiresAt (required).</param>
        /// <param name="product">product.</param>
        public LicenseSubDto(string id = default(string), string key = default(string), string status = default(string), decimal? activationLimit = default(decimal?), string activationMessage = default(string), string expiresAt = default(string), ProductSubDto product = default(ProductSubDto))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for LicenseSubDto and cannot be null");
            }
            this.Id = id;
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for LicenseSubDto and cannot be null");
            }
            this.Key = key;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for LicenseSubDto and cannot be null");
            }
            this.Status = status;
            // to ensure "activationLimit" is required (not null)
            if (activationLimit == null)
            {
                throw new ArgumentNullException("activationLimit is a required property for LicenseSubDto and cannot be null");
            }
            this.ActivationLimit = activationLimit;
            // to ensure "activationMessage" is required (not null)
            if (activationMessage == null)
            {
                throw new ArgumentNullException("activationMessage is a required property for LicenseSubDto and cannot be null");
            }
            this.ActivationMessage = activationMessage;
            // to ensure "expiresAt" is required (not null)
            if (expiresAt == null)
            {
                throw new ArgumentNullException("expiresAt is a required property for LicenseSubDto and cannot be null");
            }
            this.ExpiresAt = expiresAt;
            this.Product = product;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = true)]
        public string Key { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets ActivationLimit
        /// </summary>
        [DataMember(Name = "activationLimit", IsRequired = true, EmitDefaultValue = true)]
        public decimal? ActivationLimit { get; set; }

        /// <summary>
        /// Gets or Sets ActivationMessage
        /// </summary>
        [DataMember(Name = "activationMessage", IsRequired = true, EmitDefaultValue = true)]
        public string ActivationMessage { get; set; }

        /// <summary>
        /// Gets or Sets ExpiresAt
        /// </summary>
        [DataMember(Name = "expiresAt", IsRequired = true, EmitDefaultValue = true)]
        public string ExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets Product
        /// </summary>
        [DataMember(Name = "product", EmitDefaultValue = false)]
        public ProductSubDto Product { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LicenseSubDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ActivationLimit: ").Append(ActivationLimit).Append("\n");
            sb.Append("  ActivationMessage: ").Append(ActivationMessage).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
