/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// MeterIngestEventDto
    /// </summary>
    [DataContract(Name = "MeterIngestEventDto")]
    public partial class MeterIngestEventDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MeterIngestEventDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MeterIngestEventDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MeterIngestEventDto" /> class.
        /// </summary>
        /// <param name="eventId">Unique usage event ID for idempotency. (required).</param>
        /// <param name="customerId">Unique customer ID associated with the event. (required).</param>
        /// <param name="eventName">Event name that should match a meter eventName. (required).</param>
        /// <param name="value">Event quantity value. (default to 1M).</param>
        /// <param name="metadata">Metadata attached to the usage event..</param>
        /// <param name="timestamp">Timestamp of the event in ISO 8601 format..</param>
        public MeterIngestEventDto(string eventId = default(string), string customerId = default(string), string eventName = default(string), decimal value = 1M, Dictionary<string, Object> metadata = default(Dictionary<string, Object>), string timestamp = default(string))
        {
            // to ensure "eventId" is required (not null)
            if (eventId == null)
            {
                throw new ArgumentNullException("eventId is a required property for MeterIngestEventDto and cannot be null");
            }
            this.EventId = eventId;
            // to ensure "customerId" is required (not null)
            if (customerId == null)
            {
                throw new ArgumentNullException("customerId is a required property for MeterIngestEventDto and cannot be null");
            }
            this.CustomerId = customerId;
            // to ensure "eventName" is required (not null)
            if (eventName == null)
            {
                throw new ArgumentNullException("eventName is a required property for MeterIngestEventDto and cannot be null");
            }
            this.EventName = eventName;
            this.Value = value;
            this.Metadata = metadata;
            this.Timestamp = timestamp;
        }

        /// <summary>
        /// Unique usage event ID for idempotency.
        /// </summary>
        /// <value>Unique usage event ID for idempotency.</value>
        /*
        <example>evt_9Y3kP4qR7tU1vW2xZ5aB6c</example>
        */
        [DataMember(Name = "event_id", IsRequired = true, EmitDefaultValue = true)]
        public string EventId { get; set; }

        /// <summary>
        /// Unique customer ID associated with the event.
        /// </summary>
        /// <value>Unique customer ID associated with the event.</value>
        /*
        <example>cus_8n7m6l5k4j3h2g1f0e9d8c</example>
        */
        [DataMember(Name = "customer_id", IsRequired = true, EmitDefaultValue = true)]
        public string CustomerId { get; set; }

        /// <summary>
        /// Event name that should match a meter eventName.
        /// </summary>
        /// <value>Event name that should match a meter eventName.</value>
        /*
        <example>api.request</example>
        */
        [DataMember(Name = "event_name", IsRequired = true, EmitDefaultValue = true)]
        public string EventName { get; set; }

        /// <summary>
        /// Event quantity value.
        /// </summary>
        /// <value>Event quantity value.</value>
        /*
        <example>1</example>
        */
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public decimal Value { get; set; }

        /// <summary>
        /// Metadata attached to the usage event.
        /// </summary>
        /// <value>Metadata attached to the usage event.</value>
        /*
        <example>{plan&#x3D;enterprise, region&#x3D;asia-southeast-1}</example>
        */
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Timestamp of the event in ISO 8601 format.
        /// </summary>
        /// <value>Timestamp of the event in ISO 8601 format.</value>
        /*
        <example>2026-05-23T10:00:00.000Z</example>
        */
        [DataMember(Name = "timestamp", EmitDefaultValue = false)]
        public string Timestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MeterIngestEventDto {\n");
            sb.Append("  EventId: ").Append(EventId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  EventName: ").Append(EventName).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
