/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// OperationalWebhookEndpointResponseDto
    /// </summary>
    [DataContract(Name = "OperationalWebhookEndpointResponseDto")]
    public partial class OperationalWebhookEndpointResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OperationalWebhookEndpointResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OperationalWebhookEndpointResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OperationalWebhookEndpointResponseDto" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="url">url (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="disabled">disabled (required).</param>
        /// <param name="filterTypes">filterTypes (required).</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="throttleRate">throttleRate (required).</param>
        /// <param name="uid">uid.</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        /// <param name="secret">The endpoint&#39;s raw secret (only returned on POST creation)..</param>
        public OperationalWebhookEndpointResponseDto(string id = default(string), string url = default(string), string description = default(string), bool disabled = default(bool), List<string> filterTypes = default(List<string>), Object metadata = default(Object), decimal throttleRate = default(decimal), Object uid = default(Object), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime), string secret = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for OperationalWebhookEndpointResponseDto and cannot be null");
            }
            this.Id = id;
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for OperationalWebhookEndpointResponseDto and cannot be null");
            }
            this.Url = url;
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new ArgumentNullException("description is a required property for OperationalWebhookEndpointResponseDto and cannot be null");
            }
            this.Description = description;
            this.Disabled = disabled;
            // to ensure "filterTypes" is required (not null)
            if (filterTypes == null)
            {
                throw new ArgumentNullException("filterTypes is a required property for OperationalWebhookEndpointResponseDto and cannot be null");
            }
            this.FilterTypes = filterTypes;
            this.ThrottleRate = throttleRate;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.Metadata = metadata;
            this.Uid = uid;
            this.Secret = secret;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /*
        <example>ep_1srOrx2ZWZBpBUvZwXKQmoEYga2</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        /*
        <example>https://example.com/webhook/</example>
        */
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        /*
        <example>Production monitoring endpoint</example>
        */
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Disabled
        /// </summary>
        /*
        <example>false</example>
        */
        [DataMember(Name = "disabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Disabled { get; set; }

        /// <summary>
        /// Gets or Sets FilterTypes
        /// </summary>
        /*
        <example>[message.attempt.failing]</example>
        */
        [DataMember(Name = "filterTypes", IsRequired = true, EmitDefaultValue = true)]
        public List<string> FilterTypes { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        /*
        <example>{environment&#x3D;production}</example>
        */
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Gets or Sets ThrottleRate
        /// </summary>
        /*
        <example>0</example>
        */
        [DataMember(Name = "throttleRate", IsRequired = true, EmitDefaultValue = true)]
        public decimal ThrottleRate { get; set; }

        /// <summary>
        /// Gets or Sets Uid
        /// </summary>
        /*
        <example>monitoring-prod-endpoint</example>
        */
        [DataMember(Name = "uid", EmitDefaultValue = false)]
        public Object Uid { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /*
        <example>2026-05-30T14:11:29.071Z</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        /*
        <example>2026-05-30T14:11:29.071Z</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// The endpoint&#39;s raw secret (only returned on POST creation).
        /// </summary>
        /// <value>The endpoint&#39;s raw secret (only returned on POST creation).</value>
        /*
        <example>whsec_C2FVsBQIhrscChlQIMV+b5sSYspob7oD</example>
        */
        [DataMember(Name = "secret", EmitDefaultValue = false)]
        public string Secret { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OperationalWebhookEndpointResponseDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Disabled: ").Append(Disabled).Append("\n");
            sb.Append("  FilterTypes: ").Append(FilterTypes).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  ThrottleRate: ").Append(ThrottleRate).Append("\n");
            sb.Append("  Uid: ").Append(Uid).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  Secret: ").Append(Secret).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
