/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// OperationalWebhookEndpointHeadersResponseDto
    /// </summary>
    [DataContract(Name = "OperationalWebhookEndpointHeadersResponseDto")]
    public partial class OperationalWebhookEndpointHeadersResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OperationalWebhookEndpointHeadersResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected OperationalWebhookEndpointHeadersResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="OperationalWebhookEndpointHeadersResponseDto" /> class.
        /// </summary>
        /// <param name="headers">Key-value headers sent with the webhook. (required).</param>
        /// <param name="sensitive">List of sensitive header keys (e.g. Authorization) that are masked. (required).</param>
        public OperationalWebhookEndpointHeadersResponseDto(Object headers = default(Object), List<string> sensitive = default(List<string>))
        {
            // to ensure "headers" is required (not null)
            if (headers == null)
            {
                throw new ArgumentNullException("headers is a required property for OperationalWebhookEndpointHeadersResponseDto and cannot be null");
            }
            this.Headers = headers;
            // to ensure "sensitive" is required (not null)
            if (sensitive == null)
            {
                throw new ArgumentNullException("sensitive is a required property for OperationalWebhookEndpointHeadersResponseDto and cannot be null");
            }
            this.Sensitive = sensitive;
        }

        /// <summary>
        /// Key-value headers sent with the webhook.
        /// </summary>
        /// <value>Key-value headers sent with the webhook.</value>
        /*
        <example>{&quot;X-Example&quot;:&quot;123&quot;,&quot;X-Foobar&quot;:&quot;Bar&quot;}</example>
        */
        [DataMember(Name = "headers", IsRequired = true, EmitDefaultValue = true)]
        public Object Headers { get; set; }

        /// <summary>
        /// List of sensitive header keys (e.g. Authorization) that are masked.
        /// </summary>
        /// <value>List of sensitive header keys (e.g. Authorization) that are masked.</value>
        /*
        <example>[&quot;Authorization&quot;]</example>
        */
        [DataMember(Name = "sensitive", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Sensitive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OperationalWebhookEndpointHeadersResponseDto {\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("  Sensitive: ").Append(Sensitive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
