/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// Represents an order (payment) processed under your business, containing customer, billing, product cart, and refund details.
    /// </summary>
    [DataContract(Name = "Order")]
    public partial class Order : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Order" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Order() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Order" /> class.
        /// </summary>
        /// <param name="id">Unique internal database identifier. (required).</param>
        /// <param name="invoiceUrl">The invoice print URL. (required).</param>
        /// <param name="customer">Customer details. (required).</param>
        /// <param name="totalAmount">Total paid amount in cents. (required).</param>
        /// <param name="subtotal">Subtotal amount in cents. (required).</param>
        /// <param name="usdTotal">Total paid amount converted to USD..</param>
        /// <param name="taxAmount">Tax amount in cents. (required).</param>
        /// <param name="applicationFee">Application fee in cents. (required).</param>
        /// <param name="amountAfterFees">Net amount after fees in cents. (required).</param>
        /// <param name="currency">Currency code. (required).</param>
        /// <param name="status">Current status of the payment. (required).</param>
        /// <param name="createdAt">Payment creation timestamp. (required).</param>
        /// <param name="paidAt">Payment completion/paid timestamp..</param>
        /// <param name="paymentMethod">Payment method utilized. (required).</param>
        /// <param name="cardLastFour">Last four digits of card used..</param>
        /// <param name="cardNetwork">Card network/brand..</param>
        /// <param name="cardType">Card type..</param>
        /// <param name="billing">Billing address details..</param>
        /// <param name="productCart">Products purchased in this order. (required).</param>
        /// <param name="metadata">Custom metadata payload associated with this payment..</param>
        /// <param name="varOrder">Order details snapshot..</param>
        /// <param name="refundable">Indicates whether the order is eligible for refund. (required).</param>
        /// <param name="refunds">List of refunds associated with this payment..</param>
        /// <param name="businessId">Business unique ID identifier. (required).</param>
        /// <param name="businessName">Business display title/name. (required).</param>
        /// <param name="billingReason">Billing reason detail..</param>
        public Order(string id = default(string), string invoiceUrl = default(string), OrderCustomer customer = default(OrderCustomer), int totalAmount = default(int), int subtotal = default(int), decimal usdTotal = default(decimal), int taxAmount = default(int), int applicationFee = default(int), int amountAfterFees = default(int), string currency = default(string), string status = default(string), DateTime createdAt = default(DateTime), DateTime paidAt = default(DateTime), string paymentMethod = default(string), string cardLastFour = default(string), string cardNetwork = default(string), string cardType = default(string), OrderBilling billing = default(OrderBilling), List<OrderProductCart> productCart = default(List<OrderProductCart>), Object metadata = default(Object), OrderDetail varOrder = default(OrderDetail), bool refundable = default(bool), List<OrderRefund> refunds = default(List<OrderRefund>), string businessId = default(string), string businessName = default(string), string billingReason = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Order and cannot be null");
            }
            this.Id = id;
            // to ensure "invoiceUrl" is required (not null)
            if (invoiceUrl == null)
            {
                throw new ArgumentNullException("invoiceUrl is a required property for Order and cannot be null");
            }
            this.InvoiceUrl = invoiceUrl;
            // to ensure "customer" is required (not null)
            if (customer == null)
            {
                throw new ArgumentNullException("customer is a required property for Order and cannot be null");
            }
            this.Customer = customer;
            this.TotalAmount = totalAmount;
            this.Subtotal = subtotal;
            this.TaxAmount = taxAmount;
            this.ApplicationFee = applicationFee;
            this.AmountAfterFees = amountAfterFees;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for Order and cannot be null");
            }
            this.Currency = currency;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for Order and cannot be null");
            }
            this.Status = status;
            this.CreatedAt = createdAt;
            // to ensure "paymentMethod" is required (not null)
            if (paymentMethod == null)
            {
                throw new ArgumentNullException("paymentMethod is a required property for Order and cannot be null");
            }
            this.PaymentMethod = paymentMethod;
            // to ensure "productCart" is required (not null)
            if (productCart == null)
            {
                throw new ArgumentNullException("productCart is a required property for Order and cannot be null");
            }
            this.ProductCart = productCart;
            this.Refundable = refundable;
            // to ensure "businessId" is required (not null)
            if (businessId == null)
            {
                throw new ArgumentNullException("businessId is a required property for Order and cannot be null");
            }
            this.BusinessId = businessId;
            // to ensure "businessName" is required (not null)
            if (businessName == null)
            {
                throw new ArgumentNullException("businessName is a required property for Order and cannot be null");
            }
            this.BusinessName = businessName;
            this.UsdTotal = usdTotal;
            this.PaidAt = paidAt;
            this.CardLastFour = cardLastFour;
            this.CardNetwork = cardNetwork;
            this.CardType = cardType;
            this.Billing = billing;
            this.Metadata = metadata;
            this.VarOrder = varOrder;
            this.Refunds = refunds;
            this.BillingReason = billingReason;
        }

        /// <summary>
        /// Unique internal database identifier.
        /// </summary>
        /// <value>Unique internal database identifier.</value>
        /*
        <example>pay_123</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The invoice print URL.
        /// </summary>
        /// <value>The invoice print URL.</value>
        /*
        <example>https://solifyn.com/transactions/payments/pay_123/print</example>
        */
        [DataMember(Name = "invoice_url", IsRequired = true, EmitDefaultValue = true)]
        public string InvoiceUrl { get; set; }

        /// <summary>
        /// Customer details.
        /// </summary>
        /// <value>Customer details.</value>
        [DataMember(Name = "customer", IsRequired = true, EmitDefaultValue = true)]
        public OrderCustomer Customer { get; set; }

        /// <summary>
        /// Total paid amount in cents.
        /// </summary>
        /// <value>Total paid amount in cents.</value>
        /*
        <example>2900</example>
        */
        [DataMember(Name = "total_amount", IsRequired = true, EmitDefaultValue = true)]
        public int TotalAmount { get; set; }

        /// <summary>
        /// Subtotal amount in cents.
        /// </summary>
        /// <value>Subtotal amount in cents.</value>
        /*
        <example>2900</example>
        */
        [DataMember(Name = "subtotal", IsRequired = true, EmitDefaultValue = true)]
        public int Subtotal { get; set; }

        /// <summary>
        /// Total paid amount converted to USD.
        /// </summary>
        /// <value>Total paid amount converted to USD.</value>
        /*
        <example>30.6</example>
        */
        [DataMember(Name = "usdTotal", EmitDefaultValue = false)]
        public decimal UsdTotal { get; set; }

        /// <summary>
        /// Tax amount in cents.
        /// </summary>
        /// <value>Tax amount in cents.</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "tax_amount", IsRequired = true, EmitDefaultValue = true)]
        public int TaxAmount { get; set; }

        /// <summary>
        /// Application fee in cents.
        /// </summary>
        /// <value>Application fee in cents.</value>
        /*
        <example>150</example>
        */
        [DataMember(Name = "application_fee", IsRequired = true, EmitDefaultValue = true)]
        public int ApplicationFee { get; set; }

        /// <summary>
        /// Net amount after fees in cents.
        /// </summary>
        /// <value>Net amount after fees in cents.</value>
        /*
        <example>2750</example>
        */
        [DataMember(Name = "amount_after_fees", IsRequired = true, EmitDefaultValue = true)]
        public int AmountAfterFees { get; set; }

        /// <summary>
        /// Currency code.
        /// </summary>
        /// <value>Currency code.</value>
        /*
        <example>usd</example>
        */
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Current status of the payment.
        /// </summary>
        /// <value>Current status of the payment.</value>
        /*
        <example>paid</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Payment creation timestamp.
        /// </summary>
        /// <value>Payment creation timestamp.</value>
        /*
        <example>2026-05-22T08:00:00Z</example>
        */
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Payment completion/paid timestamp.
        /// </summary>
        /// <value>Payment completion/paid timestamp.</value>
        /*
        <example>2026-05-22T08:05:00Z</example>
        */
        [DataMember(Name = "paidAt", EmitDefaultValue = false)]
        public DateTime PaidAt { get; set; }

        /// <summary>
        /// Payment method utilized.
        /// </summary>
        /// <value>Payment method utilized.</value>
        /*
        <example>card</example>
        */
        [DataMember(Name = "payment_method", IsRequired = true, EmitDefaultValue = true)]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// Last four digits of card used.
        /// </summary>
        /// <value>Last four digits of card used.</value>
        /*
        <example>4242</example>
        */
        [DataMember(Name = "card_last_four", EmitDefaultValue = false)]
        public string CardLastFour { get; set; }

        /// <summary>
        /// Card network/brand.
        /// </summary>
        /// <value>Card network/brand.</value>
        /*
        <example>visa</example>
        */
        [DataMember(Name = "card_network", EmitDefaultValue = false)]
        public string CardNetwork { get; set; }

        /// <summary>
        /// Card type.
        /// </summary>
        /// <value>Card type.</value>
        /*
        <example>visa</example>
        */
        [DataMember(Name = "card_type", EmitDefaultValue = false)]
        public string CardType { get; set; }

        /// <summary>
        /// Billing address details.
        /// </summary>
        /// <value>Billing address details.</value>
        [DataMember(Name = "billing", EmitDefaultValue = false)]
        public OrderBilling Billing { get; set; }

        /// <summary>
        /// Products purchased in this order.
        /// </summary>
        /// <value>Products purchased in this order.</value>
        [DataMember(Name = "product_cart", IsRequired = true, EmitDefaultValue = true)]
        public List<OrderProductCart> ProductCart { get; set; }

        /// <summary>
        /// Custom metadata payload associated with this payment.
        /// </summary>
        /// <value>Custom metadata payload associated with this payment.</value>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Order details snapshot.
        /// </summary>
        /// <value>Order details snapshot.</value>
        [DataMember(Name = "order", EmitDefaultValue = false)]
        public OrderDetail VarOrder { get; set; }

        /// <summary>
        /// Indicates whether the order is eligible for refund.
        /// </summary>
        /// <value>Indicates whether the order is eligible for refund.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "refundable", IsRequired = true, EmitDefaultValue = true)]
        public bool Refundable { get; set; }

        /// <summary>
        /// List of refunds associated with this payment.
        /// </summary>
        /// <value>List of refunds associated with this payment.</value>
        [DataMember(Name = "refunds", EmitDefaultValue = false)]
        public List<OrderRefund> Refunds { get; set; }

        /// <summary>
        /// Business unique ID identifier.
        /// </summary>
        /// <value>Business unique ID identifier.</value>
        /*
        <example>biz_123</example>
        */
        [DataMember(Name = "businessId", IsRequired = true, EmitDefaultValue = true)]
        public string BusinessId { get; set; }

        /// <summary>
        /// Business display title/name.
        /// </summary>
        /// <value>Business display title/name.</value>
        /*
        <example>Acme SaaS Corp</example>
        */
        [DataMember(Name = "businessName", IsRequired = true, EmitDefaultValue = true)]
        public string BusinessName { get; set; }

        /// <summary>
        /// Billing reason detail.
        /// </summary>
        /// <value>Billing reason detail.</value>
        /*
        <example>subscription_cycle</example>
        */
        [DataMember(Name = "billing_reason", EmitDefaultValue = false)]
        public string BillingReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Order {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  InvoiceUrl: ").Append(InvoiceUrl).Append("\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  TotalAmount: ").Append(TotalAmount).Append("\n");
            sb.Append("  Subtotal: ").Append(Subtotal).Append("\n");
            sb.Append("  UsdTotal: ").Append(UsdTotal).Append("\n");
            sb.Append("  TaxAmount: ").Append(TaxAmount).Append("\n");
            sb.Append("  ApplicationFee: ").Append(ApplicationFee).Append("\n");
            sb.Append("  AmountAfterFees: ").Append(AmountAfterFees).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  PaidAt: ").Append(PaidAt).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("  CardLastFour: ").Append(CardLastFour).Append("\n");
            sb.Append("  CardNetwork: ").Append(CardNetwork).Append("\n");
            sb.Append("  CardType: ").Append(CardType).Append("\n");
            sb.Append("  Billing: ").Append(Billing).Append("\n");
            sb.Append("  ProductCart: ").Append(ProductCart).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  VarOrder: ").Append(VarOrder).Append("\n");
            sb.Append("  Refundable: ").Append(Refundable).Append("\n");
            sb.Append("  Refunds: ").Append(Refunds).Append("\n");
            sb.Append("  BusinessId: ").Append(BusinessId).Append("\n");
            sb.Append("  BusinessName: ").Append(BusinessName).Append("\n");
            sb.Append("  BillingReason: ").Append(BillingReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
