/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// PayoutAccount
    /// </summary>
    [DataContract(Name = "PayoutAccount")]
    public partial class PayoutAccount : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PayoutAccount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PayoutAccount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PayoutAccount" /> class.
        /// </summary>
        /// <param name="id">The payout account ID (required).</param>
        /// <param name="status">Status of the payout account onboarding (required).</param>
        /// <param name="capabilities">Onboarding capability status flags (e.g., transfers, payouts).</param>
        public PayoutAccount(string id = default(string), string status = default(string), Object capabilities = default(Object))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for PayoutAccount and cannot be null");
            }
            this.Id = id;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for PayoutAccount and cannot be null");
            }
            this.Status = status;
            this.Capabilities = capabilities;
        }

        /// <summary>
        /// The payout account ID
        /// </summary>
        /// <value>The payout account ID</value>
        /*
        <example>acct_123</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Status of the payout account onboarding
        /// </summary>
        /// <value>Status of the payout account onboarding</value>
        /*
        <example>active</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Onboarding capability status flags (e.g., transfers, payouts)
        /// </summary>
        /// <value>Onboarding capability status flags (e.g., transfers, payouts)</value>
        [DataMember(Name = "capabilities", EmitDefaultValue = false)]
        public Object Capabilities { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PayoutAccount {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Capabilities: ").Append(Capabilities).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
