/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// Represents a product item created under your business, containing core pricing, status, license behavior, subscription settings, and metadata details.
    /// </summary>
    [DataContract(Name = "Product")]
    public partial class Product : IValidatableObject
    {
        /// <summary>
        /// The tax classification for the product.
        /// </summary>
        /// <value>The tax classification for the product.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TaxCategoryEnum
        {
            /// <summary>
            /// Enum DigitalProducts for value: digital_products
            /// </summary>
            [EnumMember(Value = "digital_products")]
            DigitalProducts = 1,

            /// <summary>
            /// Enum Saas for value: saas
            /// </summary>
            [EnumMember(Value = "saas")]
            Saas = 2,

            /// <summary>
            /// Enum PhysicalProducts for value: physical_products
            /// </summary>
            [EnumMember(Value = "physical_products")]
            PhysicalProducts = 3,

            /// <summary>
            /// Enum Service for value: service
            /// </summary>
            [EnumMember(Value = "service")]
            Service = 4
        }


        /// <summary>
        /// The tax classification for the product.
        /// </summary>
        /// <value>The tax classification for the product.</value>
        /*
        <example>saas</example>
        */
        [DataMember(Name = "taxCategory", IsRequired = true, EmitDefaultValue = true)]
        public TaxCategoryEnum TaxCategory { get; set; }
        /// <summary>
        /// Pricing model of the product.
        /// </summary>
        /// <value>Pricing model of the product.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PricingTypeEnum
        {
            /// <summary>
            /// Enum UsageBased for value: usage_based
            /// </summary>
            [EnumMember(Value = "usage_based")]
            UsageBased = 1,

            /// <summary>
            /// Enum OneTime for value: one_time
            /// </summary>
            [EnumMember(Value = "one_time")]
            OneTime = 2,

            /// <summary>
            /// Enum Renewal for value: renewal
            /// </summary>
            [EnumMember(Value = "renewal")]
            Renewal = 3
        }


        /// <summary>
        /// Pricing model of the product.
        /// </summary>
        /// <value>Pricing model of the product.</value>
        /*
        <example>one_time</example>
        */
        [DataMember(Name = "pricingType", IsRequired = true, EmitDefaultValue = true)]
        public PricingTypeEnum PricingType { get; set; }
        /// <summary>
        /// GitHub collaborator permission level.
        /// </summary>
        /// <value>GitHub collaborator permission level.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GithubPermissionEnum
        {
            /// <summary>
            /// Enum Pull for value: pull
            /// </summary>
            [EnumMember(Value = "pull")]
            Pull = 1,

            /// <summary>
            /// Enum Triage for value: triage
            /// </summary>
            [EnumMember(Value = "triage")]
            Triage = 2,

            /// <summary>
            /// Enum Push for value: push
            /// </summary>
            [EnumMember(Value = "push")]
            Push = 3,

            /// <summary>
            /// Enum Maintain for value: maintain
            /// </summary>
            [EnumMember(Value = "maintain")]
            Maintain = 4,

            /// <summary>
            /// Enum Admin for value: admin
            /// </summary>
            [EnumMember(Value = "admin")]
            Admin = 5
        }


        /// <summary>
        /// GitHub collaborator permission level.
        /// </summary>
        /// <value>GitHub collaborator permission level.</value>
        /*
        <example>pull</example>
        */
        [DataMember(Name = "githubPermission", IsRequired = true, EmitDefaultValue = true)]
        public GithubPermissionEnum GithubPermission { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Product" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Product() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Product" /> class.
        /// </summary>
        /// <param name="id">The unique identifier (ID) of the product. (required).</param>
        /// <param name="name">The display name of the product. (required).</param>
        /// <param name="price">The price amount of the product (e.g. 29.00). (required).</param>
        /// <param name="currency">The three-letter ISO currency code (e.g. USD, VND, EUR). (required).</param>
        /// <param name="description">A comprehensive rich text description of the product..</param>
        /// <param name="status">The lifecycle status of the product (e.g. ACTIVE, ARCHIVED). (required).</param>
        /// <param name="imageUrl">URL of the product cover image. (required).</param>
        /// <param name="taxCategory">The tax classification for the product. (required).</param>
        /// <param name="pricingType">Pricing model of the product. (required).</param>
        /// <param name="discount">Discount value as a percentage or fixed amount. (required).</param>
        /// <param name="hasLicenseKey">Indicates if the product issues a cryptographically secure software license key upon checkout completion. (required).</param>
        /// <param name="hasDigitalDelivery">Whether the product includes digital file downloads upon purchase. (required).</param>
        /// <param name="hasGithubAccess">Whether the product includes GitHub repository access. (required).</param>
        /// <param name="githubRepo">GitHub repository to grant access to (format: owner/repo). (required).</param>
        /// <param name="githubPermission">GitHub collaborator permission level. (required).</param>
        /// <param name="hasDiscordAccess">Whether the product includes Discord role access. (required).</param>
        /// <param name="discordGuildId">Discord Guild (Server) ID to grant access to. (required).</param>
        /// <param name="discordRoleId">Discord Role ID to assign to the user. (required).</param>
        /// <param name="isTaxInclusive">Whether the product price already includes applicable sales taxes. (required).</param>
        /// <param name="billingPeriod">The subscription billing cycle interval in days (for subscription products). (required).</param>
        /// <param name="trialPeriodDays">Trial duration in days for subscription products. (required).</param>
        /// <param name="expirationDays">Automatic expiration period in days for the subscription entitlement. (required).</param>
        /// <param name="statementDescriptor">Custom text displayed on customer credit card statements for purchases of this product. (required).</param>
        /// <param name="payWhatYouWant">Indicates if customers are allowed to enter a custom pricing amount at checkout. (required).</param>
        /// <param name="metadata">Custom developer metadata key-value pairs associated with the product. (required).</param>
        /// <param name="customFields">Custom form field questions to ask the customer during checkout. (required).</param>
        /// <param name="stock">Available stock quantity, or null for unlimited inventory. (required).</param>
        /// <param name="activationLimit">Maximum number of simultaneous active instances/devices allowed per issued license key (applicable if hasLicenseKey is true). (required).</param>
        /// <param name="isListed">Defines if the product is listed publicly on the merchant&#39;s storefront template. (required).</param>
        /// <param name="isFree">Whether the product is free. (required).</param>
        /// <param name="createdAt">Timestamp indicating exactly when the product was created. (required).</param>
        /// <param name="updatedAt">Timestamp indicating when the product was last modified. (required).</param>
        /// <param name="isPermanentlyDeleted">Indicates if the product has been permanently deleted. (required).</param>
        /// <param name="brandId">Optional brand identifier. (required).</param>
        /// <param name="digitalLink">Secure link for digital delivery. (required).</param>
        /// <param name="instructions">Special instructions provided upon purchase. (required).</param>
        /// <param name="activationMessage">Custom message displayed when a license key is activated. (required).</param>
        /// <param name="expiryHours">Number of hours until the license key expires. (required).</param>
        /// <param name="businessId">The unique identifier of the business owning this product. (required).</param>
        public Product(Guid id = default(Guid), string name = default(string), decimal price = default(decimal), string currency = default(string), string description = default(string), string status = default(string), string imageUrl = default(string), TaxCategoryEnum taxCategory = default(TaxCategoryEnum), PricingTypeEnum pricingType = default(PricingTypeEnum), decimal discount = default(decimal), bool hasLicenseKey = default(bool), bool hasDigitalDelivery = default(bool), bool hasGithubAccess = default(bool), string githubRepo = default(string), GithubPermissionEnum githubPermission = default(GithubPermissionEnum), bool hasDiscordAccess = default(bool), string discordGuildId = default(string), string discordRoleId = default(string), bool isTaxInclusive = default(bool), int billingPeriod = default(int), int trialPeriodDays = default(int), int expirationDays = default(int), string statementDescriptor = default(string), bool payWhatYouWant = default(bool), Dictionary<string, string> metadata = default(Dictionary<string, string>), List<Object> customFields = default(List<Object>), int stock = default(int), int activationLimit = default(int), bool isListed = default(bool), bool isFree = default(bool), DateTime createdAt = default(DateTime), DateTime updatedAt = default(DateTime), bool isPermanentlyDeleted = default(bool), string brandId = default(string), string digitalLink = default(string), string instructions = default(string), string activationMessage = default(string), int expiryHours = default(int), string businessId = default(string))
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for Product and cannot be null");
            }
            this.Name = name;
            this.Price = price;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for Product and cannot be null");
            }
            this.Currency = currency;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for Product and cannot be null");
            }
            this.Status = status;
            // to ensure "imageUrl" is required (not null)
            if (imageUrl == null)
            {
                throw new ArgumentNullException("imageUrl is a required property for Product and cannot be null");
            }
            this.ImageUrl = imageUrl;
            this.TaxCategory = taxCategory;
            this.PricingType = pricingType;
            this.Discount = discount;
            this.HasLicenseKey = hasLicenseKey;
            this.HasDigitalDelivery = hasDigitalDelivery;
            this.HasGithubAccess = hasGithubAccess;
            // to ensure "githubRepo" is required (not null)
            if (githubRepo == null)
            {
                throw new ArgumentNullException("githubRepo is a required property for Product and cannot be null");
            }
            this.GithubRepo = githubRepo;
            this.GithubPermission = githubPermission;
            this.HasDiscordAccess = hasDiscordAccess;
            // to ensure "discordGuildId" is required (not null)
            if (discordGuildId == null)
            {
                throw new ArgumentNullException("discordGuildId is a required property for Product and cannot be null");
            }
            this.DiscordGuildId = discordGuildId;
            // to ensure "discordRoleId" is required (not null)
            if (discordRoleId == null)
            {
                throw new ArgumentNullException("discordRoleId is a required property for Product and cannot be null");
            }
            this.DiscordRoleId = discordRoleId;
            this.IsTaxInclusive = isTaxInclusive;
            this.BillingPeriod = billingPeriod;
            this.TrialPeriodDays = trialPeriodDays;
            this.ExpirationDays = expirationDays;
            // to ensure "statementDescriptor" is required (not null)
            if (statementDescriptor == null)
            {
                throw new ArgumentNullException("statementDescriptor is a required property for Product and cannot be null");
            }
            this.StatementDescriptor = statementDescriptor;
            this.PayWhatYouWant = payWhatYouWant;
            // to ensure "metadata" is required (not null)
            if (metadata == null)
            {
                throw new ArgumentNullException("metadata is a required property for Product and cannot be null");
            }
            this.Metadata = metadata;
            // to ensure "customFields" is required (not null)
            if (customFields == null)
            {
                throw new ArgumentNullException("customFields is a required property for Product and cannot be null");
            }
            this.CustomFields = customFields;
            this.Stock = stock;
            this.ActivationLimit = activationLimit;
            this.IsListed = isListed;
            this.IsFree = isFree;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.IsPermanentlyDeleted = isPermanentlyDeleted;
            // to ensure "brandId" is required (not null)
            if (brandId == null)
            {
                throw new ArgumentNullException("brandId is a required property for Product and cannot be null");
            }
            this.BrandId = brandId;
            // to ensure "digitalLink" is required (not null)
            if (digitalLink == null)
            {
                throw new ArgumentNullException("digitalLink is a required property for Product and cannot be null");
            }
            this.DigitalLink = digitalLink;
            // to ensure "instructions" is required (not null)
            if (instructions == null)
            {
                throw new ArgumentNullException("instructions is a required property for Product and cannot be null");
            }
            this.Instructions = instructions;
            // to ensure "activationMessage" is required (not null)
            if (activationMessage == null)
            {
                throw new ArgumentNullException("activationMessage is a required property for Product and cannot be null");
            }
            this.ActivationMessage = activationMessage;
            this.ExpiryHours = expiryHours;
            // to ensure "businessId" is required (not null)
            if (businessId == null)
            {
                throw new ArgumentNullException("businessId is a required property for Product and cannot be null");
            }
            this.BusinessId = businessId;
            this.Description = description;
        }

        /// <summary>
        /// The unique identifier (ID) of the product.
        /// </summary>
        /// <value>The unique identifier (ID) of the product.</value>
        /*
        <example>prod_9z8x7c6v5b4n</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public Guid Id { get; set; }

        /// <summary>
        /// The display name of the product.
        /// </summary>
        /// <value>The display name of the product.</value>
        /*
        <example>Enterprise SaaS Plan</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The price amount of the product (e.g. 29.00).
        /// </summary>
        /// <value>The price amount of the product (e.g. 29.00).</value>
        /*
        <example>99</example>
        */
        [DataMember(Name = "price", IsRequired = true, EmitDefaultValue = true)]
        public decimal Price { get; set; }

        /// <summary>
        /// The three-letter ISO currency code (e.g. USD, VND, EUR).
        /// </summary>
        /// <value>The three-letter ISO currency code (e.g. USD, VND, EUR).</value>
        /*
        <example>USD</example>
        */
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// A comprehensive rich text description of the product.
        /// </summary>
        /// <value>A comprehensive rich text description of the product.</value>
        /*
        <example>Unlock premium API integration, custom webhooks, dedicated server bandwidth, and priority 24/7 business-critical support tiers.</example>
        */
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// The lifecycle status of the product (e.g. ACTIVE, ARCHIVED).
        /// </summary>
        /// <value>The lifecycle status of the product (e.g. ACTIVE, ARCHIVED).</value>
        /*
        <example>ACTIVE</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// URL of the product cover image.
        /// </summary>
        /// <value>URL of the product cover image.</value>
        /*
        <example>https://assets.solifyn.com/images/products/saas-enterprise.png</example>
        */
        [DataMember(Name = "imageUrl", IsRequired = true, EmitDefaultValue = true)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Discount value as a percentage or fixed amount.
        /// </summary>
        /// <value>Discount value as a percentage or fixed amount.</value>
        /*
        <example>0</example>
        */
        [DataMember(Name = "discount", IsRequired = true, EmitDefaultValue = true)]
        public decimal Discount { get; set; }

        /// <summary>
        /// Indicates if the product issues a cryptographically secure software license key upon checkout completion.
        /// </summary>
        /// <value>Indicates if the product issues a cryptographically secure software license key upon checkout completion.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "hasLicenseKey", IsRequired = true, EmitDefaultValue = true)]
        public bool HasLicenseKey { get; set; }

        /// <summary>
        /// Whether the product includes digital file downloads upon purchase.
        /// </summary>
        /// <value>Whether the product includes digital file downloads upon purchase.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "hasDigitalDelivery", IsRequired = true, EmitDefaultValue = true)]
        public bool HasDigitalDelivery { get; set; }

        /// <summary>
        /// Whether the product includes GitHub repository access.
        /// </summary>
        /// <value>Whether the product includes GitHub repository access.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "hasGithubAccess", IsRequired = true, EmitDefaultValue = true)]
        public bool HasGithubAccess { get; set; }

        /// <summary>
        /// GitHub repository to grant access to (format: owner/repo).
        /// </summary>
        /// <value>GitHub repository to grant access to (format: owner/repo).</value>
        /*
        <example>solifyn/premium-app</example>
        */
        [DataMember(Name = "githubRepo", IsRequired = true, EmitDefaultValue = true)]
        public string GithubRepo { get; set; }

        /// <summary>
        /// Whether the product includes Discord role access.
        /// </summary>
        /// <value>Whether the product includes Discord role access.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "hasDiscordAccess", IsRequired = true, EmitDefaultValue = true)]
        public bool HasDiscordAccess { get; set; }

        /// <summary>
        /// Discord Guild (Server) ID to grant access to.
        /// </summary>
        /// <value>Discord Guild (Server) ID to grant access to.</value>
        /*
        <example>123456789012345678</example>
        */
        [DataMember(Name = "discordGuildId", IsRequired = true, EmitDefaultValue = true)]
        public string DiscordGuildId { get; set; }

        /// <summary>
        /// Discord Role ID to assign to the user.
        /// </summary>
        /// <value>Discord Role ID to assign to the user.</value>
        /*
        <example>876543210987654321</example>
        */
        [DataMember(Name = "discordRoleId", IsRequired = true, EmitDefaultValue = true)]
        public string DiscordRoleId { get; set; }

        /// <summary>
        /// Whether the product price already includes applicable sales taxes.
        /// </summary>
        /// <value>Whether the product price already includes applicable sales taxes.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "isTaxInclusive", IsRequired = true, EmitDefaultValue = true)]
        public bool IsTaxInclusive { get; set; }

        /// <summary>
        /// The subscription billing cycle interval in days (for subscription products).
        /// </summary>
        /// <value>The subscription billing cycle interval in days (for subscription products).</value>
        [DataMember(Name = "billingPeriod", IsRequired = true, EmitDefaultValue = true)]
        public int BillingPeriod { get; set; }

        /// <summary>
        /// Trial duration in days for subscription products.
        /// </summary>
        /// <value>Trial duration in days for subscription products.</value>
        [DataMember(Name = "trialPeriodDays", IsRequired = true, EmitDefaultValue = true)]
        public int TrialPeriodDays { get; set; }

        /// <summary>
        /// Automatic expiration period in days for the subscription entitlement.
        /// </summary>
        /// <value>Automatic expiration period in days for the subscription entitlement.</value>
        [DataMember(Name = "expirationDays", IsRequired = true, EmitDefaultValue = true)]
        public int ExpirationDays { get; set; }

        /// <summary>
        /// Custom text displayed on customer credit card statements for purchases of this product.
        /// </summary>
        /// <value>Custom text displayed on customer credit card statements for purchases of this product.</value>
        /*
        <example>SOLIFYN*SAAS</example>
        */
        [DataMember(Name = "statementDescriptor", IsRequired = true, EmitDefaultValue = true)]
        public string StatementDescriptor { get; set; }

        /// <summary>
        /// Indicates if customers are allowed to enter a custom pricing amount at checkout.
        /// </summary>
        /// <value>Indicates if customers are allowed to enter a custom pricing amount at checkout.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "payWhatYouWant", IsRequired = true, EmitDefaultValue = true)]
        public bool PayWhatYouWant { get; set; }

        /// <summary>
        /// Custom developer metadata key-value pairs associated with the product.
        /// </summary>
        /// <value>Custom developer metadata key-value pairs associated with the product.</value>
        /*
        <example>{tier&#x3D;enterprise, department&#x3D;engineering}</example>
        */
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = true)]
        public Dictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// Custom form field questions to ask the customer during checkout.
        /// </summary>
        /// <value>Custom form field questions to ask the customer during checkout.</value>
        /*
        <example>[{id&#x3D;57aa2241-eae4-43dc-b9ae-36069b84b2da, name&#x3D;Discord Username, order&#x3D;0, required&#x3D;true, field_type&#x3D;text, placeholder&#x3D;e.g. your_discord#1234}, {id&#x3D;c86da32a-a967-457c-815b-c3440294d70b, name&#x3D;Company Name, order&#x3D;1, required&#x3D;false, field_type&#x3D;text, placeholder&#x3D;e.g. Acme Corp (Optional)}]</example>
        */
        [DataMember(Name = "customFields", IsRequired = true, EmitDefaultValue = true)]
        public List<Object> CustomFields { get; set; }

        /// <summary>
        /// Available stock quantity, or null for unlimited inventory.
        /// </summary>
        /// <value>Available stock quantity, or null for unlimited inventory.</value>
        [DataMember(Name = "stock", IsRequired = true, EmitDefaultValue = true)]
        public int Stock { get; set; }

        /// <summary>
        /// Maximum number of simultaneous active instances/devices allowed per issued license key (applicable if hasLicenseKey is true).
        /// </summary>
        /// <value>Maximum number of simultaneous active instances/devices allowed per issued license key (applicable if hasLicenseKey is true).</value>
        /*
        <example>5</example>
        */
        [DataMember(Name = "activationLimit", IsRequired = true, EmitDefaultValue = true)]
        public int ActivationLimit { get; set; }

        /// <summary>
        /// Defines if the product is listed publicly on the merchant&#39;s storefront template.
        /// </summary>
        /// <value>Defines if the product is listed publicly on the merchant&#39;s storefront template.</value>
        /*
        <example>true</example>
        */
        [DataMember(Name = "isListed", IsRequired = true, EmitDefaultValue = true)]
        public bool IsListed { get; set; }

        /// <summary>
        /// Whether the product is free.
        /// </summary>
        /// <value>Whether the product is free.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "isFree", IsRequired = true, EmitDefaultValue = true)]
        public bool IsFree { get; set; }

        /// <summary>
        /// Timestamp indicating exactly when the product was created.
        /// </summary>
        /// <value>Timestamp indicating exactly when the product was created.</value>
        /*
        <example>2026-05-18T12:00:00.000Z</example>
        */
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Timestamp indicating when the product was last modified.
        /// </summary>
        /// <value>Timestamp indicating when the product was last modified.</value>
        /*
        <example>2026-05-18T12:00:00.000Z</example>
        */
        [DataMember(Name = "updatedAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Indicates if the product has been permanently deleted.
        /// </summary>
        /// <value>Indicates if the product has been permanently deleted.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "isPermanentlyDeleted", IsRequired = true, EmitDefaultValue = true)]
        public bool IsPermanentlyDeleted { get; set; }

        /// <summary>
        /// Optional brand identifier.
        /// </summary>
        /// <value>Optional brand identifier.</value>
        /*
        <example>brd_4e29285b8sdf34ff51e07d4</example>
        */
        [DataMember(Name = "brandId", IsRequired = true, EmitDefaultValue = true)]
        public string BrandId { get; set; }

        /// <summary>
        /// Secure link for digital delivery.
        /// </summary>
        /// <value>Secure link for digital delivery.</value>
        [DataMember(Name = "digitalLink", IsRequired = true, EmitDefaultValue = true)]
        public string DigitalLink { get; set; }

        /// <summary>
        /// Special instructions provided upon purchase.
        /// </summary>
        /// <value>Special instructions provided upon purchase.</value>
        /*
        <example>Log in to your Solifyn developer dashboard and enter your license key to activate the premium SaaS resources.</example>
        */
        [DataMember(Name = "instructions", IsRequired = true, EmitDefaultValue = true)]
        public string Instructions { get; set; }

        /// <summary>
        /// Custom message displayed when a license key is activated.
        /// </summary>
        /// <value>Custom message displayed when a license key is activated.</value>
        /*
        <example>Activation successful. Welcome to the Solifyn Enterprise Plan!</example>
        */
        [DataMember(Name = "activationMessage", IsRequired = true, EmitDefaultValue = true)]
        public string ActivationMessage { get; set; }

        /// <summary>
        /// Number of hours until the license key expires.
        /// </summary>
        /// <value>Number of hours until the license key expires.</value>
        /*
        <example>8760</example>
        */
        [DataMember(Name = "expiryHours", IsRequired = true, EmitDefaultValue = true)]
        public int ExpiryHours { get; set; }

        /// <summary>
        /// The unique identifier of the business owning this product.
        /// </summary>
        /// <value>The unique identifier of the business owning this product.</value>
        /*
        <example>biz_4r5t6y7u8i9o</example>
        */
        [DataMember(Name = "businessId", IsRequired = true, EmitDefaultValue = true)]
        public string BusinessId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Product {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  TaxCategory: ").Append(TaxCategory).Append("\n");
            sb.Append("  PricingType: ").Append(PricingType).Append("\n");
            sb.Append("  Discount: ").Append(Discount).Append("\n");
            sb.Append("  HasLicenseKey: ").Append(HasLicenseKey).Append("\n");
            sb.Append("  HasDigitalDelivery: ").Append(HasDigitalDelivery).Append("\n");
            sb.Append("  HasGithubAccess: ").Append(HasGithubAccess).Append("\n");
            sb.Append("  GithubRepo: ").Append(GithubRepo).Append("\n");
            sb.Append("  GithubPermission: ").Append(GithubPermission).Append("\n");
            sb.Append("  HasDiscordAccess: ").Append(HasDiscordAccess).Append("\n");
            sb.Append("  DiscordGuildId: ").Append(DiscordGuildId).Append("\n");
            sb.Append("  DiscordRoleId: ").Append(DiscordRoleId).Append("\n");
            sb.Append("  IsTaxInclusive: ").Append(IsTaxInclusive).Append("\n");
            sb.Append("  BillingPeriod: ").Append(BillingPeriod).Append("\n");
            sb.Append("  TrialPeriodDays: ").Append(TrialPeriodDays).Append("\n");
            sb.Append("  ExpirationDays: ").Append(ExpirationDays).Append("\n");
            sb.Append("  StatementDescriptor: ").Append(StatementDescriptor).Append("\n");
            sb.Append("  PayWhatYouWant: ").Append(PayWhatYouWant).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("  Stock: ").Append(Stock).Append("\n");
            sb.Append("  ActivationLimit: ").Append(ActivationLimit).Append("\n");
            sb.Append("  IsListed: ").Append(IsListed).Append("\n");
            sb.Append("  IsFree: ").Append(IsFree).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  IsPermanentlyDeleted: ").Append(IsPermanentlyDeleted).Append("\n");
            sb.Append("  BrandId: ").Append(BrandId).Append("\n");
            sb.Append("  DigitalLink: ").Append(DigitalLink).Append("\n");
            sb.Append("  Instructions: ").Append(Instructions).Append("\n");
            sb.Append("  ActivationMessage: ").Append(ActivationMessage).Append("\n");
            sb.Append("  ExpiryHours: ").Append(ExpiryHours).Append("\n");
            sb.Append("  BusinessId: ").Append(BusinessId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
