/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// Represents a customer subscription membership resource, containing current billing terms, plan, status, and metadata.
    /// </summary>
    [DataContract(Name = "Subscription")]
    public partial class Subscription : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Subscription" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Subscription() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Subscription" /> class.
        /// </summary>
        /// <param name="id">The unique ID of the subscription (required).</param>
        /// <param name="status">The status of the subscription (e.g. completed, active, trialing, past_due, canceled) (required).</param>
        /// <param name="createdAt">Timestamp when the subscription was created (required).</param>
        /// <param name="joinedAt">Timestamp when the member joined (required).</param>
        /// <param name="updatedAt">Timestamp when the subscription was last updated (required).</param>
        /// <param name="manageUrl">The management URL for the billing/subscription (required).</param>
        /// <param name="member">The member details (required).</param>
        /// <param name="user">The user details (required).</param>
        /// <param name="renewalPeriodStart">Start timestamp of the current renewal period (required).</param>
        /// <param name="renewalPeriodEnd">End timestamp of the current renewal period (required).</param>
        /// <param name="cancelAtPeriodEnd">Whether the subscription is set to cancel at the end of the billing period (required).</param>
        /// <param name="cancelOption">The cancel option details (required).</param>
        /// <param name="cancellationReason">The reason for cancellation (required).</param>
        /// <param name="canceledAt">Timestamp when the subscription was canceled (required).</param>
        /// <param name="currency">The currency used for payments (required).</param>
        /// <param name="company">The company context details (required).</param>
        /// <param name="plan">The plan associated with this subscription (required).</param>
        /// <param name="promoCode">The promo code applied to the subscription (required).</param>
        /// <param name="product">The product associated with the subscription (required).</param>
        /// <param name="licenseKey">The license key associated with this subscription (required).</param>
        /// <param name="metadata">Additional metadata for the subscription (required).</param>
        /// <param name="paymentCollectionPaused">Whether the payment collection is currently paused (required).</param>
        /// <param name="checkoutConfigurationId">The checkout configuration ID used (required).</param>
        /// <param name="price">The price/amount of the membership.</param>
        /// <param name="type">The type of the membership plan.</param>
        /// <param name="customerId">The business customer ID.</param>
        public Subscription(string id = default(string), string status = default(string), DateTime createdAt = default(DateTime), DateTime joinedAt = default(DateTime), DateTime updatedAt = default(DateTime), string manageUrl = default(string), SubscriptionMemberDto member = default(SubscriptionMemberDto), SubscriptionUserDto user = default(SubscriptionUserDto), Object renewalPeriodStart = default(Object), Object renewalPeriodEnd = default(Object), bool cancelAtPeriodEnd = default(bool), Object cancelOption = default(Object), Object cancellationReason = default(Object), Object canceledAt = default(Object), string currency = default(string), SubscriptionCompanyDto company = default(SubscriptionCompanyDto), SubscriptionPlanDto plan = default(SubscriptionPlanDto), Object promoCode = default(Object), SubscriptionProductDto product = default(SubscriptionProductDto), Object licenseKey = default(Object), Object metadata = default(Object), bool paymentCollectionPaused = default(bool), string checkoutConfigurationId = default(string), Object price = default(Object), Object type = default(Object), Object customerId = default(Object))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Subscription and cannot be null");
            }
            this.Id = id;
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for Subscription and cannot be null");
            }
            this.Status = status;
            this.CreatedAt = createdAt;
            this.JoinedAt = joinedAt;
            this.UpdatedAt = updatedAt;
            // to ensure "manageUrl" is required (not null)
            if (manageUrl == null)
            {
                throw new ArgumentNullException("manageUrl is a required property for Subscription and cannot be null");
            }
            this.ManageUrl = manageUrl;
            // to ensure "member" is required (not null)
            if (member == null)
            {
                throw new ArgumentNullException("member is a required property for Subscription and cannot be null");
            }
            this.Member = member;
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for Subscription and cannot be null");
            }
            this.User = user;
            // to ensure "renewalPeriodStart" is required (not null)
            if (renewalPeriodStart == null)
            {
                throw new ArgumentNullException("renewalPeriodStart is a required property for Subscription and cannot be null");
            }
            this.RenewalPeriodStart = renewalPeriodStart;
            // to ensure "renewalPeriodEnd" is required (not null)
            if (renewalPeriodEnd == null)
            {
                throw new ArgumentNullException("renewalPeriodEnd is a required property for Subscription and cannot be null");
            }
            this.RenewalPeriodEnd = renewalPeriodEnd;
            this.CancelAtPeriodEnd = cancelAtPeriodEnd;
            // to ensure "cancelOption" is required (not null)
            if (cancelOption == null)
            {
                throw new ArgumentNullException("cancelOption is a required property for Subscription and cannot be null");
            }
            this.CancelOption = cancelOption;
            // to ensure "cancellationReason" is required (not null)
            if (cancellationReason == null)
            {
                throw new ArgumentNullException("cancellationReason is a required property for Subscription and cannot be null");
            }
            this.CancellationReason = cancellationReason;
            // to ensure "canceledAt" is required (not null)
            if (canceledAt == null)
            {
                throw new ArgumentNullException("canceledAt is a required property for Subscription and cannot be null");
            }
            this.CanceledAt = canceledAt;
            // to ensure "currency" is required (not null)
            if (currency == null)
            {
                throw new ArgumentNullException("currency is a required property for Subscription and cannot be null");
            }
            this.Currency = currency;
            // to ensure "company" is required (not null)
            if (company == null)
            {
                throw new ArgumentNullException("company is a required property for Subscription and cannot be null");
            }
            this.Company = company;
            // to ensure "plan" is required (not null)
            if (plan == null)
            {
                throw new ArgumentNullException("plan is a required property for Subscription and cannot be null");
            }
            this.Plan = plan;
            // to ensure "promoCode" is required (not null)
            if (promoCode == null)
            {
                throw new ArgumentNullException("promoCode is a required property for Subscription and cannot be null");
            }
            this.PromoCode = promoCode;
            // to ensure "product" is required (not null)
            if (product == null)
            {
                throw new ArgumentNullException("product is a required property for Subscription and cannot be null");
            }
            this.Product = product;
            // to ensure "licenseKey" is required (not null)
            if (licenseKey == null)
            {
                throw new ArgumentNullException("licenseKey is a required property for Subscription and cannot be null");
            }
            this.LicenseKey = licenseKey;
            // to ensure "metadata" is required (not null)
            if (metadata == null)
            {
                throw new ArgumentNullException("metadata is a required property for Subscription and cannot be null");
            }
            this.Metadata = metadata;
            this.PaymentCollectionPaused = paymentCollectionPaused;
            // to ensure "checkoutConfigurationId" is required (not null)
            if (checkoutConfigurationId == null)
            {
                throw new ArgumentNullException("checkoutConfigurationId is a required property for Subscription and cannot be null");
            }
            this.CheckoutConfigurationId = checkoutConfigurationId;
            this.Price = price;
            this.Type = type;
            this.CustomerId = customerId;
        }

        /// <summary>
        /// The unique ID of the subscription
        /// </summary>
        /// <value>The unique ID of the subscription</value>
        /*
        <example>mem_123</example>
        */
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The status of the subscription (e.g. completed, active, trialing, past_due, canceled)
        /// </summary>
        /// <value>The status of the subscription (e.g. completed, active, trialing, past_due, canceled)</value>
        /*
        <example>active</example>
        */
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public string Status { get; set; }

        /// <summary>
        /// Timestamp when the subscription was created
        /// </summary>
        /// <value>Timestamp when the subscription was created</value>
        /*
        <example>2025-01-01T12:00:00.000Z</example>
        */
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Timestamp when the member joined
        /// </summary>
        /// <value>Timestamp when the member joined</value>
        /*
        <example>2025-01-01T12:00:00.000Z</example>
        */
        [DataMember(Name = "joined_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime JoinedAt { get; set; }

        /// <summary>
        /// Timestamp when the subscription was last updated
        /// </summary>
        /// <value>Timestamp when the subscription was last updated</value>
        /*
        <example>2025-01-01T12:00:00.000Z</example>
        */
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// The management URL for the billing/subscription
        /// </summary>
        /// <value>The management URL for the billing/subscription</value>
        /*
        <example>https://example.com/billing/manage/mber_123</example>
        */
        [DataMember(Name = "manage_url", IsRequired = true, EmitDefaultValue = true)]
        public string ManageUrl { get; set; }

        /// <summary>
        /// The member details
        /// </summary>
        /// <value>The member details</value>
        [DataMember(Name = "member", IsRequired = true, EmitDefaultValue = true)]
        public SubscriptionMemberDto Member { get; set; }

        /// <summary>
        /// The user details
        /// </summary>
        /// <value>The user details</value>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public SubscriptionUserDto User { get; set; }

        /// <summary>
        /// Start timestamp of the current renewal period
        /// </summary>
        /// <value>Start timestamp of the current renewal period</value>
        [DataMember(Name = "renewal_period_start", IsRequired = true, EmitDefaultValue = true)]
        public Object RenewalPeriodStart { get; set; }

        /// <summary>
        /// End timestamp of the current renewal period
        /// </summary>
        /// <value>End timestamp of the current renewal period</value>
        [DataMember(Name = "renewal_period_end", IsRequired = true, EmitDefaultValue = true)]
        public Object RenewalPeriodEnd { get; set; }

        /// <summary>
        /// Whether the subscription is set to cancel at the end of the billing period
        /// </summary>
        /// <value>Whether the subscription is set to cancel at the end of the billing period</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "cancel_at_period_end", IsRequired = true, EmitDefaultValue = true)]
        public bool CancelAtPeriodEnd { get; set; }

        /// <summary>
        /// The cancel option details
        /// </summary>
        /// <value>The cancel option details</value>
        [DataMember(Name = "cancel_option", IsRequired = true, EmitDefaultValue = true)]
        public Object CancelOption { get; set; }

        /// <summary>
        /// The reason for cancellation
        /// </summary>
        /// <value>The reason for cancellation</value>
        [DataMember(Name = "cancellation_reason", IsRequired = true, EmitDefaultValue = true)]
        public Object CancellationReason { get; set; }

        /// <summary>
        /// Timestamp when the subscription was canceled
        /// </summary>
        /// <value>Timestamp when the subscription was canceled</value>
        [DataMember(Name = "canceled_at", IsRequired = true, EmitDefaultValue = true)]
        public Object CanceledAt { get; set; }

        /// <summary>
        /// The currency used for payments
        /// </summary>
        /// <value>The currency used for payments</value>
        /*
        <example>usd</example>
        */
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// The company context details
        /// </summary>
        /// <value>The company context details</value>
        [DataMember(Name = "company", IsRequired = true, EmitDefaultValue = true)]
        public SubscriptionCompanyDto Company { get; set; }

        /// <summary>
        /// The plan associated with this subscription
        /// </summary>
        /// <value>The plan associated with this subscription</value>
        [DataMember(Name = "plan", IsRequired = true, EmitDefaultValue = true)]
        public SubscriptionPlanDto Plan { get; set; }

        /// <summary>
        /// The promo code applied to the subscription
        /// </summary>
        /// <value>The promo code applied to the subscription</value>
        [DataMember(Name = "promo_code", IsRequired = true, EmitDefaultValue = true)]
        public Object PromoCode { get; set; }

        /// <summary>
        /// The product associated with the subscription
        /// </summary>
        /// <value>The product associated with the subscription</value>
        [DataMember(Name = "product", IsRequired = true, EmitDefaultValue = true)]
        public SubscriptionProductDto Product { get; set; }

        /// <summary>
        /// The license key associated with this subscription
        /// </summary>
        /// <value>The license key associated with this subscription</value>
        [DataMember(Name = "license_key", IsRequired = true, EmitDefaultValue = true)]
        public Object LicenseKey { get; set; }

        /// <summary>
        /// Additional metadata for the subscription
        /// </summary>
        /// <value>Additional metadata for the subscription</value>
        /*
        <example>{&quot;is_usage_based&quot;:&quot;false&quot;}</example>
        */
        [DataMember(Name = "metadata", IsRequired = true, EmitDefaultValue = true)]
        public Object Metadata { get; set; }

        /// <summary>
        /// Whether the payment collection is currently paused
        /// </summary>
        /// <value>Whether the payment collection is currently paused</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "payment_collection_paused", IsRequired = true, EmitDefaultValue = true)]
        public bool PaymentCollectionPaused { get; set; }

        /// <summary>
        /// The checkout configuration ID used
        /// </summary>
        /// <value>The checkout configuration ID used</value>
        /*
        <example>ch_123</example>
        */
        [DataMember(Name = "checkout_configuration_id", IsRequired = true, EmitDefaultValue = true)]
        public string CheckoutConfigurationId { get; set; }

        /// <summary>
        /// The price/amount of the membership
        /// </summary>
        /// <value>The price/amount of the membership</value>
        /*
        <example>99</example>
        */
        [DataMember(Name = "price", EmitDefaultValue = false)]
        public Object Price { get; set; }

        /// <summary>
        /// The type of the membership plan
        /// </summary>
        /// <value>The type of the membership plan</value>
        /*
        <example>renewal</example>
        */
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public Object Type { get; set; }

        /// <summary>
        /// The business customer ID
        /// </summary>
        /// <value>The business customer ID</value>
        /*
        <example>cust_123</example>
        */
        [DataMember(Name = "customerId", EmitDefaultValue = false)]
        public Object CustomerId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Subscription {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  JoinedAt: ").Append(JoinedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  ManageUrl: ").Append(ManageUrl).Append("\n");
            sb.Append("  Member: ").Append(Member).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  RenewalPeriodStart: ").Append(RenewalPeriodStart).Append("\n");
            sb.Append("  RenewalPeriodEnd: ").Append(RenewalPeriodEnd).Append("\n");
            sb.Append("  CancelAtPeriodEnd: ").Append(CancelAtPeriodEnd).Append("\n");
            sb.Append("  CancelOption: ").Append(CancelOption).Append("\n");
            sb.Append("  CancellationReason: ").Append(CancellationReason).Append("\n");
            sb.Append("  CanceledAt: ").Append(CanceledAt).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("  Plan: ").Append(Plan).Append("\n");
            sb.Append("  PromoCode: ").Append(PromoCode).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  LicenseKey: ").Append(LicenseKey).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  PaymentCollectionPaused: ").Append(PaymentCollectionPaused).Append("\n");
            sb.Append("  CheckoutConfigurationId: ").Append(CheckoutConfigurationId).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
