/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// SupportedCurrenciesResponseDto
    /// </summary>
    [DataContract(Name = "SupportedCurrenciesResponseDto")]
    public partial class SupportedCurrenciesResponseDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SupportedCurrenciesResponseDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SupportedCurrenciesResponseDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SupportedCurrenciesResponseDto" /> class.
        /// </summary>
        /// <param name="label">The label display name of the currency (required).</param>
        /// <param name="value">The currency code (required).</param>
        public SupportedCurrenciesResponseDto(string label = default(string), string value = default(string))
        {
            // to ensure "label" is required (not null)
            if (label == null)
            {
                throw new ArgumentNullException("label is a required property for SupportedCurrenciesResponseDto and cannot be null");
            }
            this.Label = label;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for SupportedCurrenciesResponseDto and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// The label display name of the currency
        /// </summary>
        /// <value>The label display name of the currency</value>
        /*
        <example>US Dollar</example>
        */
        [DataMember(Name = "label", IsRequired = true, EmitDefaultValue = true)]
        public string Label { get; set; }

        /// <summary>
        /// The currency code
        /// </summary>
        /// <value>The currency code</value>
        /*
        <example>usd</example>
        */
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SupportedCurrenciesResponseDto {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
