/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Solifyn.Client.OpenAPIDateConverter;

namespace Solifyn.Model
{
    /// <summary>
    /// WithdrawalList
    /// </summary>
    [DataContract(Name = "WithdrawalList")]
    public partial class WithdrawalList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WithdrawalList" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WithdrawalList() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WithdrawalList" /> class.
        /// </summary>
        /// <param name="items">List of withdrawals (required).</param>
        /// <param name="totalCount">Total count of withdrawals matching filters (required).</param>
        public WithdrawalList(List<Withdrawal> items = default(List<Withdrawal>), decimal totalCount = default(decimal))
        {
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for WithdrawalList and cannot be null");
            }
            this.Items = items;
            this.TotalCount = totalCount;
        }

        /// <summary>
        /// List of withdrawals
        /// </summary>
        /// <value>List of withdrawals</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<Withdrawal> Items { get; set; }

        /// <summary>
        /// Total count of withdrawals matching filters
        /// </summary>
        /// <value>Total count of withdrawals matching filters</value>
        /*
        <example>5</example>
        */
        [DataMember(Name = "total_count", IsRequired = true, EmitDefaultValue = true)]
        public decimal TotalCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WithdrawalList {\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
