/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Solifyn.Client;
using Solifyn.Api;
// uncomment below to import models
//using Solifyn.Model;

namespace Solifyn.Test.Api
{
    /// <summary>
    ///  Class for testing DeveloperApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DeveloperApiTests : IDisposable
    {
        private DeveloperApi instance;

        public DeveloperApiTests()
        {
            instance = new DeveloperApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeveloperApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DeveloperApi
            //Assert.IsType<DeveloperApi>(instance);
        }

        /// <summary>
        /// Test DeveloperCreateApiKey
        /// </summary>
        [Fact]
        public void DeveloperCreateApiKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateApiKeyDto createApiKeyDto = null;
            //var response = instance.DeveloperCreateApiKey(createApiKeyDto);
            //Assert.IsType<ApiKeyResponseDto>(response);
        }

        /// <summary>
        /// Test DeveloperCreateWebhook
        /// </summary>
        [Fact]
        public void DeveloperCreateWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateWebhookEndpointDto createWebhookEndpointDto = null;
            //var response = instance.DeveloperCreateWebhook(createWebhookEndpointDto);
            //Assert.IsType<WebhookEndpointResponseDto>(response);
        }

        /// <summary>
        /// Test DeveloperDeleteWebhook
        /// </summary>
        [Fact]
        public void DeveloperDeleteWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DeveloperDeleteWebhook(id);
        }

        /// <summary>
        /// Test DeveloperGetAppPortal
        /// </summary>
        [Fact]
        public void DeveloperGetAppPortalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DeveloperGetAppPortal();
            //Assert.IsType<AppPortalUrlResponseDto>(response);
        }

        /// <summary>
        /// Test DeveloperGetWebhook
        /// </summary>
        [Fact]
        public void DeveloperGetWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DeveloperGetWebhook(id);
            //Assert.IsType<WebhookEndpointResponseDto>(response);
        }

        /// <summary>
        /// Test DeveloperListApiKeys
        /// </summary>
        [Fact]
        public void DeveloperListApiKeysTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DeveloperListApiKeys();
            //Assert.IsType<List<ApiKeyResponseDto>>(response);
        }

        /// <summary>
        /// Test DeveloperListWebhookDeliveries
        /// </summary>
        [Fact]
        public void DeveloperListWebhookDeliveriesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DeveloperListWebhookDeliveries(id);
            //Assert.IsType<List<WebhookDeliveryResponseDto>>(response);
        }

        /// <summary>
        /// Test DeveloperListWebhooks
        /// </summary>
        [Fact]
        public void DeveloperListWebhooksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DeveloperListWebhooks();
            //Assert.IsType<List<WebhookEndpointResponseDto>>(response);
        }

        /// <summary>
        /// Test DeveloperRevokeApiKey
        /// </summary>
        [Fact]
        public void DeveloperRevokeApiKeyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DeveloperRevokeApiKey(id);
        }

        /// <summary>
        /// Test DeveloperUpdateWebhook
        /// </summary>
        [Fact]
        public void DeveloperUpdateWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UpdateWebhookEndpointDto updateWebhookEndpointDto = null;
            //var response = instance.DeveloperUpdateWebhook(id, updateWebhookEndpointDto);
            //Assert.IsType<WebhookEndpointResponseDto>(response);
        }
    }
}
