/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Solifyn.Client;
using Solifyn.Api;

namespace Solifyn.Test.Api
{
    /// <summary>
    ///  Class for testing DigitalFileApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DigitalFileApiTests : IDisposable
    {
        private DigitalFileApi instance;

        public DigitalFileApiTests()
        {
            instance = new DigitalFileApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DigitalFileApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DigitalFileApi
            //Assert.IsType<DigitalFileApi>(instance);
        }

        /// <summary>
        /// Test DigitalFileControllerCreate
        /// </summary>
        [Fact]
        public void DigitalFileControllerCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DigitalFileControllerCreate();
        }

        /// <summary>
        /// Test DigitalFileControllerFindAll
        /// </summary>
        [Fact]
        public void DigitalFileControllerFindAllTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.DigitalFileControllerFindAll();
        }

        /// <summary>
        /// Test DigitalFileControllerRemove
        /// </summary>
        [Fact]
        public void DigitalFileControllerRemoveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.DigitalFileControllerRemove(id);
        }
    }
}
