/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Solifyn.Client;
using Solifyn.Api;
// uncomment below to import models
//using Solifyn.Model;

namespace Solifyn.Test.Api
{
    /// <summary>
    ///  Class for testing DisputesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DisputesApiTests : IDisposable
    {
        private DisputesApi instance;

        public DisputesApiTests()
        {
            instance = new DisputesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DisputesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DisputesApi
            //Assert.IsType<DisputesApi>(instance);
        }

        /// <summary>
        /// Test DisputesGenerateReport
        /// </summary>
        [Fact]
        public void DisputesGenerateReportTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string createdAtGte = null;
            //string createdAtLte = null;
            //string status = null;
            //instance.DisputesGenerateReport(createdAtGte, createdAtLte, status);
        }

        /// <summary>
        /// Test DisputesGet
        /// </summary>
        [Fact]
        public void DisputesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DisputesGet(id);
            //Assert.IsType<Dispute>(response);
        }

        /// <summary>
        /// Test DisputesList
        /// </summary>
        [Fact]
        public void DisputesListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string page = null;
            //string limit = null;
            //string status = null;
            //string type = null;
            //var response = instance.DisputesList(page, limit, status, type);
            //Assert.IsType<DisputeList>(response);
        }

        /// <summary>
        /// Test DisputesSubmitEvidence
        /// </summary>
        [Fact]
        public void DisputesSubmitEvidenceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DisputesSubmitEvidence(id);
            //Assert.IsType<Dispute>(response);
        }

        /// <summary>
        /// Test DisputesUpdateEvidence
        /// </summary>
        [Fact]
        public void DisputesUpdateEvidenceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //DisputeEvidenceUpdate disputeEvidenceUpdate = null;
            //var response = instance.DisputesUpdateEvidence(id, disputeEvidenceUpdate);
            //Assert.IsType<Dispute>(response);
        }

        /// <summary>
        /// Test DisputesUploadEvidenceFile
        /// </summary>
        [Fact]
        public void DisputesUploadEvidenceFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream file = null;
            //var response = instance.DisputesUploadEvidenceFile(file);
            //Assert.IsType<DisputeFileUpload>(response);
        }
    }
}
