/*
 * Solifyn API
 *
 * Welcome to the Solifyn API Reference. Leverage our secure endpoints to manage products and issue, validate, and manage software license keys programmatically.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Solifyn.Client;
using Solifyn.Api;
// uncomment below to import models
//using Solifyn.Model;

namespace Solifyn.Test.Api
{
    /// <summary>
    ///  Class for testing ProductsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProductsApiTests : IDisposable
    {
        private ProductsApi instance;

        public ProductsApiTests()
        {
            instance = new ProductsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProductsApi
            //Assert.IsType<ProductsApi>(instance);
        }

        /// <summary>
        /// Test ProductsArchive
        /// </summary>
        [Fact]
        public void ProductsArchiveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ProductsArchive(id);
            //Assert.IsType<ProductsArchive200Response>(response);
        }

        /// <summary>
        /// Test ProductsCreate
        /// </summary>
        [Fact]
        public void ProductsCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProductCreate productCreate = null;
            //var response = instance.ProductsCreate(productCreate);
            //Assert.IsType<Product>(response);
        }

        /// <summary>
        /// Test ProductsGet
        /// </summary>
        [Fact]
        public void ProductsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ProductsGet(id);
            //Assert.IsType<Product>(response);
        }

        /// <summary>
        /// Test ProductsList
        /// </summary>
        [Fact]
        public void ProductsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string pricingType = null;
            //string sorting = null;
            //decimal? limit = null;
            //decimal? page = null;
            //bool? isRecurring = null;
            //bool? isArchived = null;
            //string query = null;
            //string id = null;
            //var response = instance.ProductsList(pricingType, sorting, limit, page, isRecurring, isArchived, query, id);
            //Assert.IsType<ProductsList200Response>(response);
        }

        /// <summary>
        /// Test ProductsUnarchive
        /// </summary>
        [Fact]
        public void ProductsUnarchiveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ProductsUnarchive(id);
            //Assert.IsType<ProductsUnarchive200Response>(response);
        }

        /// <summary>
        /// Test ProductsUpdate
        /// </summary>
        [Fact]
        public void ProductsUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //ProductUpdate productUpdate = null;
            //var response = instance.ProductsUpdate(id, productUpdate);
            //Assert.IsType<ProductMessageResponseDto>(response);
        }
    }
}
